# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/chromecast/failed_cast_attempt.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/chromecast/failed_cast_attempt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+client/chromecast/failed_cast_attempt.proto\x12\x11\x63lient.chromecast\"1\n\x1b\x46\x61iledCastAttemptProperties\x12\x12\n\nerror_code\x18\x01 \x01(\tBu\n)com.hotstar.event.model.client.chromecastP\x01ZFgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/chromecastb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.chromecast.failed_cast_attempt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n)com.hotstar.event.model.client.chromecastP\001ZFgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/chromecast'
  _globals['_FAILEDCASTATTEMPTPROPERTIES']._serialized_start=66
  _globals['_FAILEDCASTATTEMPTPROPERTIES']._serialized_end=115
# @@protoc_insertion_point(module_scope)
