# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/chromecast/viewed_casting_device_list.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/chromecast/viewed_casting_device_list.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2client/chromecast/viewed_casting_device_list.proto\x12\x11\x63lient.chromecast\"N\n!ViewedCastingDeviceListProperties\x12\x14\n\x0c\x64\x65vice_count\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65vice_list\x18\x02 \x01(\tBu\n)com.hotstar.event.model.client.chromecastP\x01ZFgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/chromecastb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.chromecast.viewed_casting_device_list_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n)com.hotstar.event.model.client.chromecastP\001ZFgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/chromecast'
  _globals['_VIEWEDCASTINGDEVICELISTPROPERTIES']._serialized_start=73
  _globals['_VIEWEDCASTINGDEVICELISTPROPERTIES']._serialized_end=151
# @@protoc_insertion_point(module_scope)
