# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feature/communication/data/search_zero_filter_data.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'feature/communication/data/search_zero_filter_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8feature/communication/data/search_zero_filter_data.proto\x12\x1a\x66\x65\x61ture.communication.data\"A\n\x14SearchZeroFilterData\x12\x15\n\tfilter_id\x18\x01 \x01(\tB\x02\x18\x01\x12\x12\n\nwidget_url\x18\x02 \x01(\tBw\n/com.hotstar.ui.model.feature.communication.dataP\x01ZBgithub.com/hotstar/hs-core-ui-models-go/feature/communication/datab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feature.communication.data.search_zero_filter_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n/com.hotstar.ui.model.feature.communication.dataP\001ZBgithub.com/hotstar/hs-core-ui-models-go/feature/communication/data'
  _globals['_SEARCHZEROFILTERDATA'].fields_by_name['filter_id']._loaded_options = None
  _globals['_SEARCHZEROFILTERDATA'].fields_by_name['filter_id']._serialized_options = b'\030\001'
  _globals['_SEARCHZEROFILTERDATA']._serialized_start=88
  _globals['_SEARCHZEROFILTERDATA']._serialized_end=153
# @@protoc_insertion_point(module_scope)
