# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: composable/base/corner_radius.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'composable/base/corner_radius.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from composable.tokens import dls_tokens_pb2 as composable_dot_tokens_dot_dls__tokens__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#composable/base/corner_radius.proto\x12\ncomposable\x1a\"composable/tokens/dls_tokens.proto\"\xd0\x01\n\x0c\x43ornerRadius\x12.\n\x08topStart\x18\x01 \x01(\x0e\x32\x1c.composable.tokens.DLSRadius\x12,\n\x06topEnd\x18\x02 \x01(\x0e\x32\x1c.composable.tokens.DLSRadius\x12\x31\n\x0b\x62ottomStart\x18\x03 \x01(\x0e\x32\x1c.composable.tokens.DLSRadius\x12/\n\tbottomEnd\x18\x04 \x01(\x0e\x32\x1c.composable.tokens.DLSRadiusB\\\n\x1f\x63om.hotstar.ui.model.composableP\x01Z7github.com/hotstar/hs-core-ui-models-go/composable/baseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'composable.base.corner_radius_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037com.hotstar.ui.model.composableP\001Z7github.com/hotstar/hs-core-ui-models-go/composable/base'
  _globals['_CORNERRADIUS']._serialized_start=88
  _globals['_CORNERRADIUS']._serialized_end=296
# @@protoc_insertion_point(module_scope)
