# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/feature/device/orientation.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'api/feature/device/orientation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$api/feature/device/orientation.proto\x12\x12\x61pi.feature.device\"I\n\x0bOrientation\x12:\n\x0borientation\x18\x01 \x01(\x0e\x32%.api.feature.device.ScreenOrientation*z\n\x11ScreenOrientation\x12\"\n\x1eSCREEN_ORIENTATION_UNSPECIFIED\x10\x00\x12\x1f\n\x1bSCREEN_ORIENTATION_PORTRAIT\x10\x01\x12 \n\x1cSCREEN_ORIENTATION_LANDSCAPE\x10\x02\x42w\n*com.hotstar.event.model.api.feature.deviceP\x01ZGgithub.com/hotstar/data-event-schemas-go/hsanalytics/api/feature/deviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.feature.device.orientation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*com.hotstar.event.model.api.feature.deviceP\001ZGgithub.com/hotstar/data-event-schemas-go/hsanalytics/api/feature/device'
  _globals['_SCREENORIENTATION']._serialized_start=135
  _globals['_SCREENORIENTATION']._serialized_end=257
  _globals['_ORIENTATION']._serialized_start=60
  _globals['_ORIENTATION']._serialized_end=133
# @@protoc_insertion_point(module_scope)
