# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/feature/device/partner_family.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'api/feature/device/partner_family.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'api/feature/device/partner_family.proto\x12\x12\x61pi.feature.device\x1a google/protobuf/descriptor.proto*\x97\x01\n\rPartnerFamily\x12\x1e\n\x1aPARTNER_FAMILY_UNSPECIFIED\x10\x00\x12\x16\n\x12PARTNER_FAMILY_MCA\x10\x01\x12\x18\n\x14PARTNER_FAMILY_VIDAA\x10\x02\x12\x18\n\x14PARTNER_FAMILY_ASTRO\x10\x03\x12\x1a\n\x16PARTNER_FAMILY_COOLITA\x10\x04\x42w\n*com.hotstar.event.model.api.feature.deviceP\x01ZGgithub.com/hotstar/data-event-schemas-go/hsanalytics/api/feature/deviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.feature.device.partner_family_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*com.hotstar.event.model.api.feature.deviceP\001ZGgithub.com/hotstar/data-event-schemas-go/hsanalytics/api/feature/device'
  _globals['_PARTNERFAMILY']._serialized_start=98
  _globals['_PARTNERFAMILY']._serialized_end=249
# @@protoc_insertion_point(module_scope)
