# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: action/show_tooltip.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'action/show_tooltip.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from feature.tooltip import arrow_alignment_pb2 as feature_dot_tooltip_dot_arrow__alignment__pb2
from feature.tooltip import content_spread_pb2 as feature_dot_tooltip_dot_content__spread__pb2
from feature.tooltip import arrow_position_pb2 as feature_dot_tooltip_dot_arrow__position__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61\x63tion/show_tooltip.proto\x12\x06\x61\x63tion\x1a%feature/tooltip/arrow_alignment.proto\x1a$feature/tooltip/content_spread.proto\x1a$feature/tooltip/arrow_position.proto\"\x9a\x03\n\x11ShowTooltipAction\x12\x13\n\x07message\x18\x01 \x01(\tB\x02\x18\x01\x12\x42\n\x19preferred_arrow_alignment\x18\x02 \x01(\x0e\x32\x1f.feature.tooltip.ArrowAlignment\x12\x36\n\x0e\x63ontent_spread\x18\x03 \x01(\x0e\x32\x1e.feature.tooltip.ContentSpread\x12\x36\n\x0e\x61rrow_position\x18\x04 \x01(\x0e\x32\x1e.feature.tooltip.ArrowPosition\x12,\n\x04\x64\x61ta\x18\x05 \x01(\x0b\x32\x1e.action.ShowTooltipAction.Data\x12;\n\x0ctooltip_type\x18\x06 \x01(\x0e\x32%.action.ShowTooltipAction.TooltipType\x1a\x17\n\x04\x44\x61ta\x12\x0f\n\x07message\x18\x02 \x01(\t\"8\n\x0bTooltipType\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x08\n\x04TEXT\x10\x01\x12\x12\n\x0eUSER_REACTIONS\x10\x02\x42O\n\x1b\x63om.hotstar.ui.model.actionP\x01Z.github.com/hotstar/hs-core-ui-models-go/actionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'action.show_tooltip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.actionP\001Z.github.com/hotstar/hs-core-ui-models-go/action'
  _globals['_SHOWTOOLTIPACTION'].fields_by_name['message']._loaded_options = None
  _globals['_SHOWTOOLTIPACTION'].fields_by_name['message']._serialized_options = b'\030\001'
  _globals['_SHOWTOOLTIPACTION']._serialized_start=153
  _globals['_SHOWTOOLTIPACTION']._serialized_end=563
  _globals['_SHOWTOOLTIPACTION_DATA']._serialized_start=482
  _globals['_SHOWTOOLTIPACTION_DATA']._serialized_end=505
  _globals['_SHOWTOOLTIPACTION_TOOLTIPTYPE']._serialized_start=507
  _globals['_SHOWTOOLTIPACTION_TOOLTIPTYPE']._serialized_end=563
# @@protoc_insertion_point(module_scope)
