# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: action/update_cache.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'action/update_cache.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from feature.commons import widget_wrapper_pb2 as feature_dot_commons_dot_widget__wrapper__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61\x63tion/update_cache.proto\x12\x06\x61\x63tion\x1a$feature/commons/widget_wrapper.proto\"\xbe\x02\n\x11UpdateCacheAction\x12\x36\n\toperation\x18\x01 \x01(\x0e\x32#.action.UpdateCacheAction.Operation\x12\x32\n\x07payload\x18\x02 \x01(\x0b\x32!.action.UpdateCacheAction.Payload\x12\x1c\n\x10\x63\x61\x63he_identifier\x18\x03 \x01(\tB\x02\x18\x01\x12\x10\n\x08\x63\x61\x63he_id\x18\x04 \x01(\x04\x1aK\n\x07Payload\x12\x38\n\x0ewidget_wrapper\x18\x01 \x01(\x0b\x32\x1e.feature.commons.WidgetWrapperH\x00\x42\x06\n\x04\x64\x61ta\"<\n\tOperation\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x07\n\x03\x41\x44\x44\x10\x01\x12\n\n\x06REMOVE\x10\x02\x12\t\n\x05RESET\x10\x03:\x02\x18\x01\x42O\n\x1b\x63om.hotstar.ui.model.actionP\x01Z.github.com/hotstar/hs-core-ui-models-go/actionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'action.update_cache_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.actionP\001Z.github.com/hotstar/hs-core-ui-models-go/action'
  _globals['_UPDATECACHEACTION'].fields_by_name['cache_identifier']._loaded_options = None
  _globals['_UPDATECACHEACTION'].fields_by_name['cache_identifier']._serialized_options = b'\030\001'
  _globals['_UPDATECACHEACTION']._loaded_options = None
  _globals['_UPDATECACHEACTION']._serialized_options = b'\030\001'
  _globals['_UPDATECACHEACTION']._serialized_start=76
  _globals['_UPDATECACHEACTION']._serialized_end=394
  _globals['_UPDATECACHEACTION_PAYLOAD']._serialized_start=253
  _globals['_UPDATECACHEACTION_PAYLOAD']._serialized_end=328
  _globals['_UPDATECACHEACTION_OPERATION']._serialized_start=330
  _globals['_UPDATECACHEACTION_OPERATION']._serialized_end=390
# @@protoc_insertion_point(module_scope)
