# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/identity/properties/buffered_onboarding_video.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/identity/properties/buffered_onboarding_video.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from client.identity.properties import video_bg_info_pb2 as client_dot_identity_dot_properties_dot_video__bg__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:client/identity/properties/buffered_onboarding_video.proto\x12\x1a\x63lient.identity.properties\x1a.client/identity/properties/video_bg_info.proto\"\xef\x01\n\x17\x42ufferedOnboardingVideo\x12\x1c\n\x14video_buffered_count\x18\x01 \x01(\x05\x12\x41\n\x0cnetwork_type\x18\x02 \x01(\x0e\x32\'.client.identity.properties.NetworkTypeB\x02\x18\x01\x12\x19\n\rnetwork_speed\x18\x03 \x01(\rB\x02\x18\x01\x12;\n\x0bscreen_size\x18\x04 \x01(\x0b\x32&.client.identity.properties.ScreenSize\x12\x1b\n\x13network_speed_in_mb\x18\x05 \x01(\x02\x42\x87\x01\n2com.hotstar.event.model.client.identity.propertiesP\x01ZOgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/identity/propertiesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.identity.properties.buffered_onboarding_video_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n2com.hotstar.event.model.client.identity.propertiesP\001ZOgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/identity/properties'
  _globals['_BUFFEREDONBOARDINGVIDEO'].fields_by_name['network_type']._loaded_options = None
  _globals['_BUFFEREDONBOARDINGVIDEO'].fields_by_name['network_type']._serialized_options = b'\030\001'
  _globals['_BUFFEREDONBOARDINGVIDEO'].fields_by_name['network_speed']._loaded_options = None
  _globals['_BUFFEREDONBOARDINGVIDEO'].fields_by_name['network_speed']._serialized_options = b'\030\001'
  _globals['_BUFFEREDONBOARDINGVIDEO']._serialized_start=139
  _globals['_BUFFEREDONBOARDINGVIDEO']._serialized_end=378
# @@protoc_insertion_point(module_scope)
