# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v2/subcontrollers/login/login_device_meta.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'v2/subcontrollers/login/login_device_meta.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/v2/subcontrollers/login/login_device_meta.proto\x12\rfeature.login\"&\n\x0fLoginDeviceMeta\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x01(\tBa\n\"com.hotstar.ui.model.feature.loginP\x01Z9github.com/hotstar/hs-core-api-go/v2/subcontrollers/loginb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v2.subcontrollers.login.login_device_meta_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"com.hotstar.ui.model.feature.loginP\001Z9github.com/hotstar/hs-core-api-go/v2/subcontrollers/login'
  _globals['_LOGINDEVICEMETA']._serialized_start=66
  _globals['_LOGINDEVICEMETA']._serialized_end=104
# @@protoc_insertion_point(module_scope)
