# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: component/subs/membership_summary_details.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'component/subs/membership_summary_details.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from component.subs import purchase_nudge_details_pb2 as component_dot_subs_dot_purchase__nudge__details__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/component/subs/membership_summary_details.proto\x12\x0e\x63omponent.subs\x1a+component/subs/purchase_nudge_details.proto\"\xfc\x03\n\x18MembershipSummaryDetails\x12\x11\n\tplan_name\x18\x01 \x01(\t\x12\x13\n\x0b\x63oupon_code\x18\x02 \x01(\t\x12\x44\n\titem_type\x18\x03 \x01(\x0e\x32\x31.component.subs.MembershipSummaryDetails.ItemType\x12\x42\n\nnudge_type\x18\x04 \x01(\x0e\x32..component.subs.PurchaseNudgeDetails.NudgeType\x12P\n\x0foffer_animation\x18\x05 \x01(\x0e\x32\x37.component.subs.MembershipSummaryDetails.OfferAnimation\"^\n\x08ItemType\x12\x19\n\x15ITEM_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n\x18ITEM_TYPE_PURCHASE_NUDGE\x10\x01\x12\x19\n\x15ITEM_TYPE_ACTIVE_PLAN\x10\x02\"|\n\x0eOfferAnimation\x12\x1f\n\x1bOFFER_ANIMATION_UNSPECIFIED\x10\x00\x12#\n\x1fOFFER_ANIMATION_ELIGIBLE_HIDDEN\x10\x01\x12$\n OFFER_ANIMATION_ELIGIBLE_VISIBLE\x10\x02\x42j\n!com.hotstar.event.model.componentP\x01ZCgithub.com/hotstar/data-event-schemas-go/hsanalytics/component/subsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'component.subs.membership_summary_details_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.hotstar.event.model.componentP\001ZCgithub.com/hotstar/data-event-schemas-go/hsanalytics/component/subs'
  _globals['_MEMBERSHIPSUMMARYDETAILS']._serialized_start=113
  _globals['_MEMBERSHIPSUMMARYDETAILS']._serialized_end=621
  _globals['_MEMBERSHIPSUMMARYDETAILS_ITEMTYPE']._serialized_start=401
  _globals['_MEMBERSHIPSUMMARYDETAILS_ITEMTYPE']._serialized_end=495
  _globals['_MEMBERSHIPSUMMARYDETAILS_OFFERANIMATION']._serialized_start=497
  _globals['_MEMBERSHIPSUMMARYDETAILS_OFFERANIMATION']._serialized_end=621
# @@protoc_insertion_point(module_scope)
