# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: component/subs/purchase_nudge_details.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'component/subs/purchase_nudge_details.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+component/subs/purchase_nudge_details.proto\x12\x0e\x63omponent.subs\"\xc5\x05\n\x14PurchaseNudgeDetails\x12\x42\n\nnudge_type\x18\x01 \x01(\x0e\x32..component.subs.PurchaseNudgeDetails.NudgeType\x12\x46\n\x0cnudge_layout\x18\x02 \x01(\x0e\x32\x30.component.subs.PurchaseNudgeDetails.NudgeLayout\x12\x14\n\x0c\x64\x65vice_count\x18\x03 \x01(\x05\x12\x46\n\x0c\x66\x65\x61ture_type\x18\x04 \x01(\x0e\x32\x30.component.subs.PurchaseNudgeDetails.FeatureType\"\x94\x02\n\tNudgeType\x12\x1a\n\x16NUDGE_TYPE_UNSPECIFIED\x10\x00\x12\x18\n\x14NUDGE_TYPE_SUBSCRIBE\x10\x01\x12\x16\n\x12NUDGE_TYPE_UPGRADE\x10\x02\x12\x14\n\x10NUDGE_TYPE_RENEW\x10\x03\x12\x11\n\rNUDGE_TYPE_DR\x10\x04\x12\x15\n\x11NUDGE_TYPE_PLAYER\x10\x05\x12\x19\n\x15NUDGE_TYPE_FREE_TRIAL\x10\x06\x12\x19\n\x15NUDGE_TYPE_PLAYER_VOD\x10\x07\x12\x1c\n\x18NUDGE_TYPE_PARTNER_OFFER\x10\x08\x12%\n!NUDGE_TYPE_MIGRATION_SUBS_CALLOUT\x10\t\"`\n\x0bNudgeLayout\x12\x1c\n\x18NUDGE_LAYOUT_UNSPECIFIED\x10\x00\x12\x1a\n\x16NUDGE_LAYOUT_DECOUPLED\x10\x01\x12\x17\n\x13NUDGE_LAYOUT_NESTED\x10\x02\"J\n\x0b\x46\x65\x61tureType\x12\x1c\n\x18\x46\x45\x41TURE_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n\x19\x46\x45\x41TURE_TYPE_FREE_PREVIEW\x10\x01\x42j\n!com.hotstar.event.model.componentP\x01ZCgithub.com/hotstar/data-event-schemas-go/hsanalytics/component/subsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'component.subs.purchase_nudge_details_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.hotstar.event.model.componentP\001ZCgithub.com/hotstar/data-event-schemas-go/hsanalytics/component/subs'
  _globals['_PURCHASENUDGEDETAILS']._serialized_start=64
  _globals['_PURCHASENUDGEDETAILS']._serialized_end=773
  _globals['_PURCHASENUDGEDETAILS_NUDGETYPE']._serialized_start=323
  _globals['_PURCHASENUDGEDETAILS_NUDGETYPE']._serialized_end=599
  _globals['_PURCHASENUDGEDETAILS_NUDGELAYOUT']._serialized_start=601
  _globals['_PURCHASENUDGEDETAILS_NUDGELAYOUT']._serialized_end=697
  _globals['_PURCHASENUDGEDETAILS_FEATURETYPE']._serialized_start=699
  _globals['_PURCHASENUDGEDETAILS_FEATURETYPE']._serialized_end=773
# @@protoc_insertion_point(module_scope)
