# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/heartbeat/heartbeat.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/heartbeat/heartbeat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from client.heartbeat.model import payload_pb2 as client_dot_heartbeat_dot_model_dot_payload__pb2
from client.player.model import client_capabilities_pb2 as client_dot_player_dot_model_dot_client__capabilities__pb2
from client.player.model import player_and_device_info_pb2 as client_dot_player_dot_model_dot_player__and__device__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n client/heartbeat/heartbeat.proto\x12\x10\x63lient.heartbeat\x1a$client/heartbeat/model/payload.proto\x1a-client/player/model/client_capabilities.proto\x1a\x30\x63lient/player/model/player_and_device_info.proto\"\x85\x02\n\x13HeartbeatProperties\x12\x31\n\x08payloads\x18\x01 \x03(\x0b\x32\x1f.client.heartbeat.model.Payload\x12H\n\x0bplayer_name\x18\x02 \x01(\x0e\x32\x33.client.player.model.PlayerAndDeviceInfo.PlayerName\x12\x16\n\x0eplayer_version\x18\x03 \x01(\t\x12\x44\n\x13\x63lient_capabilities\x18\x04 \x01(\x0b\x32\'.client.player.model.ClientCapabilities\x12\x13\n\x0bssai_cohort\x18\x05 \x01(\tBs\n(com.hotstar.event.model.client.heartbeatP\x01ZEgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/heartbeatb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.heartbeat.heartbeat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.hotstar.event.model.client.heartbeatP\001ZEgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/heartbeat'
  _globals['_HEARTBEATPROPERTIES']._serialized_start=190
  _globals['_HEARTBEATPROPERTIES']._serialized_end=451
# @@protoc_insertion_point(module_scope)
