# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/search/submitted_survey.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/search/submitted_survey.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$client/search/submitted_survey.proto\x12\rclient.search\"\xcd\x01\n\x19SubmittedSurveyProperties\x12\x17\n\x0fsurvey_question\x18\x01 \x01(\t\x12\x32\n\rresponse_list\x18\x02 \x01(\x0b\x32\x1b.client.search.ResponseList\x12\x1f\n\x17selected_response_count\x18\x03 \x01(\r\x12\x1b\n\x13user_written_review\x18\x04 \x01(\t\x12\x12\n\nquery_text\x18\x05 \x01(\t\x12\x11\n\tpage_type\x18\x06 \x01(\t\"!\n\x0cResponseList\x12\x11\n\tresponses\x18\x01 \x03(\tBm\n%com.hotstar.event.model.client.searchP\x01ZBgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/searchb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.search.submitted_survey_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.hotstar.event.model.client.searchP\001ZBgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/search'
  _globals['_SUBMITTEDSURVEYPROPERTIES']._serialized_start=56
  _globals['_SUBMITTEDSURVEYPROPERTIES']._serialized_end=261
  _globals['_RESPONSELIST']._serialized_start=263
  _globals['_RESPONSELIST']._serialized_end=296
# @@protoc_insertion_point(module_scope)
