# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: composable/elements/button_tile.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'composable/elements/button_tile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from composable.elements import text_pb2 as composable_dot_elements_dot_text__pb2
from feature.accessibility import accessibility_pb2 as feature_dot_accessibility_dot_accessibility__pb2
from base import actions_pb2 as base_dot_actions__pb2
from composable.elements import image_pb2 as composable_dot_elements_dot_image__pb2
from composable.elements import icon_pb2 as composable_dot_elements_dot_icon__pb2
from composable.elements import media_pb2 as composable_dot_elements_dot_media__pb2
from composable.base import commons_pb2 as composable_dot_base_dot_commons__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%composable/elements/button_tile.proto\x12\ncomposable\x1a\x1e\x63omposable/elements/text.proto\x1a)feature/accessibility/accessibility.proto\x1a\x12\x62\x61se/actions.proto\x1a\x1f\x63omposable/elements/image.proto\x1a\x1e\x63omposable/elements/icon.proto\x1a\x1f\x63omposable/elements/media.proto\x1a\x1d\x63omposable/base/commons.proto\"\xa3\x02\n\x0e\x42uttonTileView\x12\x33\n\x07\x63ontent\x18\x01 \x01(\x0b\x32\".composable.ButtonTileView.Content\x12\x1f\n\x05label\x18\x02 \x01(\x0b\x32\x10.composable.Text\x12;\n\raccessibility\x18\x04 \x01(\x0b\x32$.feature.accessibility.Accessibility\x1a~\n\x07\x43ontent\x12 \n\x04icon\x18\x01 \x01(\x0b\x32\x10.composable.IconH\x00\x12\"\n\x05image\x18\x02 \x01(\x0b\x32\x11.composable.ImageH\x00\x12\"\n\x05media\x18\x03 \x01(\x0b\x32\x11.composable.MediaH\x00\x42\t\n\x07\x63ontent\"\x91\x01\n\nButtonTile\x12(\n\x04view\x18\x01 \x01(\x0b\x32\x1a.composable.ButtonTileView\x12\x39\n\x12\x63omposable_commons\x18\x02 \x01(\x0b\x32\x1d.composable.ComposableCommons\x12\x1e\n\x07\x61\x63tions\x18\x03 \x01(\x0b\x32\r.base.ActionsB`\n\x1f\x63om.hotstar.ui.model.composableP\x01Z;github.com/hotstar/hs-core-ui-models-go/composable/elementsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'composable.elements.button_tile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037com.hotstar.ui.model.composableP\001Z;github.com/hotstar/hs-core-ui-models-go/composable/elements'
  _globals['_BUTTONTILEVIEW']._serialized_start=278
  _globals['_BUTTONTILEVIEW']._serialized_end=569
  _globals['_BUTTONTILEVIEW_CONTENT']._serialized_start=443
  _globals['_BUTTONTILEVIEW_CONTENT']._serialized_end=569
  _globals['_BUTTONTILE']._serialized_start=572
  _globals['_BUTTONTILE']._serialized_end=717
# @@protoc_insertion_point(module_scope)
