# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/watch/card_clicked.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/watch/card_clicked.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from client.watch import card_type_pb2 as client_dot_watch_dot_card__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63lient/watch/card_clicked.proto\x12\x0c\x63lient.watch\x1a\x1c\x63lient/watch/card_type.proto\"\xca\x01\n\x0b\x43\x61rdClicked\x12\x12\n\nevent_name\x18\x01 \x01(\t\x12)\n\tcard_type\x18\x02 \x01(\x0e\x32\x16.client.watch.CardType\x12\x15\n\rcard_position\x18\x03 \x01(\x05\x12\x16\n\x0e\x63\x61rd_createdat\x18\x04 \x01(\x03\x12\x16\n\x0e\x63\x61rd_clickedat\x18\x05 \x01(\x03\x12\x10\n\x08\x63\x61rd_cta\x18\x06 \x01(\t\x12\x12\n\ncard_title\x18\x07 \x01(\t\x12\x0f\n\x07\x63\x61rd_id\x18\x08 \x01(\tBk\n$com.hotstar.event.model.client.watchP\x01ZAgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/watchb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.watch.card_clicked_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.hotstar.event.model.client.watchP\001ZAgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/watch'
  _globals['_CARDCLICKED']._serialized_start=80
  _globals['_CARDCLICKED']._serialized_end=282
# @@protoc_insertion_point(module_scope)
