# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/watch/clicked_maxview_mode_switcher.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/watch/clicked_maxview_mode_switcher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from client.player.model import playback_mode_info_pb2 as client_dot_player_dot_model_dot_playback__mode__info__pb2
from client.player.model import stream_mode_pb2 as client_dot_player_dot_model_dot_stream__mode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0client/watch/clicked_maxview_mode_switcher.proto\x12\x0c\x63lient.watch\x1a,client/player/model/playback_mode_info.proto\x1a%client/player/model/stream_mode.proto\"\xea\x01\n$ClickedMaxviewModeSwitcherProperties\x12-\n\x04mode\x18\x01 \x01(\x0e\x32\x1f.client.player.model.StreamMode\x12\x42\n\x12player_orientation\x18\x02 \x01(\x0e\x32&.client.player.model.PlayerOrientation\x12\x14\n\x0cstream_state\x18\x03 \x01(\t\x12\x39\n\x07trigger\x18\x04 \x01(\x0e\x32(.client.watch.MaxviewModeSwitcherTrigger*\xae\x01\n\x1aMaxviewModeSwitcherTrigger\x12-\n)MAXVIEW_MODE_SWITCHER_TRIGGER_UNSPECIFIED\x10\x00\x12,\n(MAXVIEW_MODE_SWITCHER_TRIGGER_TOGGLE_CTA\x10\x01\x12\x33\n/MAXVIEW_MODE_SWITCHER_TRIGGER_HORIZONTAL_EXPAND\x10\x02\x42k\n$com.hotstar.event.model.client.watchP\x01ZAgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/watchb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.watch.clicked_maxview_mode_switcher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.hotstar.event.model.client.watchP\001ZAgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/watch'
  _globals['_MAXVIEWMODESWITCHERTRIGGER']._serialized_start=389
  _globals['_MAXVIEWMODESWITCHERTRIGGER']._serialized_end=563
  _globals['_CLICKEDMAXVIEWMODESWITCHERPROPERTIES']._serialized_start=152
  _globals['_CLICKEDMAXVIEWMODESWITCHERPROPERTIES']._serialized_end=386
# @@protoc_insertion_point(module_scope)
