# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/perf/page_content_loaded_properties.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/perf/page_content_loaded_properties.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from client.perf import page_content_loaded_commons_pb2 as client_dot_perf_dot_page__content__loaded__commons__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0client/perf/page_content_loaded_properties.proto\x12\x0b\x63lient.perf\x1a-client/perf/page_content_loaded_commons.proto\x1a\x19google/protobuf/any.proto\"_\n\x1bPageContentLoadedProperties\x12@\n\x11\x63ommon_properties\x18\x01 \x01(\x0b\x32%.client.perf.PageContentLoadedCommonsBi\n#com.hotstar.event.model.client.perfP\x01Z@github.com/hotstar/data-event-schemas-go/hsanalytics/client/perfb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.perf.page_content_loaded_properties_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.hotstar.event.model.client.perfP\001Z@github.com/hotstar/data-event-schemas-go/hsanalytics/client/perf'
  _globals['_PAGECONTENTLOADEDPROPERTIES']._serialized_start=139
  _globals['_PAGECONTENTLOADEDPROPERTIES']._serialized_end=234
# @@protoc_insertion_point(module_scope)
