# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/perf/page_loaded_properties.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/perf/page_loaded_properties.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from client.perf import page_loaded_commons_pb2 as client_dot_perf_dot_page__loaded__commons__pb2
from client.perf import watch_page_loaded_properties_v2_pb2 as client_dot_perf_dot_watch__page__loaded__properties__v2__pb2
from client.preload import preload_journey_pb2 as client_dot_preload_dot_preload__journey__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(client/perf/page_loaded_properties.proto\x12\x0b\x63lient.perf\x1a%client/perf/page_loaded_commons.proto\x1a\x31\x63lient/perf/watch_page_loaded_properties_v2.proto\x1a$client/preload/preload_journey.proto\x1a\x19google/protobuf/any.proto\"\xad\x02\n\x14PageLoadedProperties\x12\x39\n\x11\x63ommon_properties\x18\x01 \x01(\x0b\x32\x1e.client.perf.PageLoadedCommons\x12\x34\n\x16\x63ustom_page_properties\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x35\n\x0epreload_source\x18\x03 \x01(\x0b\x32\x1d.client.preload.PreloadSource\x12P\n\x1cwatch_page_loaded_properties\x18\x04 \x01(\x0b\x32(.client.perf.WatchPageLoadedPropertiesV2H\x00\x42\x1b\n\x19\x63ustom_page_properties_v2Bi\n#com.hotstar.event.model.client.perfP\x01Z@github.com/hotstar/data-event-schemas-go/hsanalytics/client/perfb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.perf.page_loaded_properties_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.hotstar.event.model.client.perfP\001Z@github.com/hotstar/data-event-schemas-go/hsanalytics/client/perf'
  _globals['_PAGELOADEDPROPERTIES']._serialized_start=213
  _globals['_PAGELOADEDPROPERTIES']._serialized_end=514
# @@protoc_insertion_point(module_scope)
