# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/identity/sna_event_props.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/identity/sna_event_props.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from component.identity import sna_event_props_pb2 as component_dot_identity_dot_sna__event__props__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%client/identity/sna_event_props.proto\x12\x0f\x63lient.identity\x1a(component/identity/sna_event_props.proto\"W\n\x14SnaEventPropsWrapper\x12?\n\x14sna_event_properties\x18\x01 \x01(\x0b\x32!.component.identity.SnaEventPropsBq\n\'com.hotstar.event.model.client.identityP\x01ZDgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/identityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.identity.sna_event_props_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'com.hotstar.event.model.client.identityP\001ZDgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/identity'
  _globals['_SNAEVENTPROPSWRAPPER']._serialized_start=100
  _globals['_SNAEVENTPROPSWRAPPER']._serialized_end=187
# @@protoc_insertion_point(module_scope)
