# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feature/remind_me/remind_me_info.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'feature/remind_me/remind_me_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import actions_pb2 as base_dot_actions__pb2
from feature.accessibility import accessibility_pb2 as feature_dot_accessibility_dot_accessibility__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&feature/remind_me/remind_me_info.proto\x12\x11\x66\x65\x61ture.remind_me\x1a\x12\x62\x61se/actions.proto\x1a)feature/accessibility/accessibility.proto\"\xe2\x01\n\x0cReminderInfo\x12\x12\n\ncontent_id\x18\x01 \x01(\t\x12\x17\n\x0fis_reminder_set\x18\x02 \x01(\x08\x12\x14\n\x0crelease_meta\x18\x03 \x01(\t\x12\x1e\n\x07\x61\x63tions\x18\x04 \x01(\x0b\x32\r.base.Actions\x12\x35\n\x07\x61lt_add\x18\x05 \x01(\x0b\x32$.feature.accessibility.Accessibility\x12\x38\n\nalt_remove\x18\x06 \x01(\x0b\x32$.feature.accessibility.AccessibilityBe\n&com.hotstar.ui.model.feature.remind_meP\x01Z9github.com/hotstar/hs-core-ui-models-go/feature/remind_meb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feature.remind_me.remind_me_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n&com.hotstar.ui.model.feature.remind_meP\001Z9github.com/hotstar/hs-core-ui-models-go/feature/remind_me'
  _globals['_REMINDERINFO']._serialized_start=125
  _globals['_REMINDERINFO']._serialized_end=351
# @@protoc_insertion_point(module_scope)
