# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feature/player/subtitle_asset.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'feature/player/subtitle_asset.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#feature/player/subtitle_asset.proto\x12\x0e\x66\x65\x61ture.player\"E\n\rSubtitleAsset\x12\x15\n\rlanguage_name\x18\x01 \x01(\t\x12\x10\n\x08iso3code\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\tB_\n#com.hotstar.ui.model.feature.playerP\x01Z6github.com/hotstar/hs-core-ui-models-go/feature/playerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feature.player.subtitle_asset_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.hotstar.ui.model.feature.playerP\001Z6github.com/hotstar/hs-core-ui-models-go/feature/player'
  _globals['_SUBTITLEASSET']._serialized_start=55
  _globals['_SUBTITLEASSET']._serialized_end=124
# @@protoc_insertion_point(module_scope)
