# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feature/sports/player_one_line_stats.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'feature/sports/player_one_line_stats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from feature.sports import player_pb2 as feature_dot_sports_dot_player__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*feature/sports/player_one_line_stats.proto\x12\x0e\x66\x65\x61ture.sports\x1a\x1b\x66\x65\x61ture/sports/player.proto\"T\n\x12PlayerOneLineStats\x12&\n\x06player\x18\x01 \x01(\x0b\x32\x16.feature.sports.Player\x12\x16\n\x0eone_line_stats\x18\x02 \x01(\tB_\n#com.hotstar.ui.model.feature.sportsP\x01Z6github.com/hotstar/hs-core-ui-models-go/feature/sportsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feature.sports.player_one_line_stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.hotstar.ui.model.feature.sportsP\001Z6github.com/hotstar/hs-core-ui-models-go/feature/sports'
  _globals['_PLAYERONELINESTATS']._serialized_start=91
  _globals['_PLAYERONELINESTATS']._serialized_end=175
# @@protoc_insertion_point(module_scope)
