# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/download/model/download_activity_name.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/download/model/download_activity_name.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2client/download/model/download_activity_name.proto\x12\x15\x63lient.download.model*\x91\x05\n\x14\x44ownloadActivityName\x12&\n\"DOWNLOAD_ACTIVITY_NAME_UNSPECIFIED\x10\x00\x12&\n\"DOWNLOAD_ACTIVITY_NAME_SAVED_TO_DB\x10\x01\x12\x32\n.DOWNLOAD_ACTIVITY_NAME_CHECK_DOWNLOAD_BFF_CALL\x10\x02\x12\x32\n.DOWNLOAD_ACTIVITY_NAME_START_DOWNLOAD_BFF_CALL\x10\x03\x12+\n\'DOWNLOAD_ACTIVITY_NAME_SIZE_CALCULATION\x10\x04\x12-\n)DOWNLOAD_ACTIVITY_NAME_DRM_KEY_DOWNLOADED\x10\x05\x12+\n\'DOWNLOAD_ACTIVITY_NAME_STARTED_DOWNLOAD\x10\x06\x12*\n&DOWNLOAD_ACTIVITY_NAME_PAUSED_DOWNLOAD\x10\x07\x12+\n\'DOWNLOAD_ACTIVITY_NAME_RESUMED_DOWNLOAD\x10\x08\x12+\n\'DOWNLOAD_ACTIVITY_NAME_STOPPED_DOWNLOAD\x10\t\x12+\n\'DOWNLOAD_ACTIVITY_NAME_DELETED_DOWNLOAD\x10\n\x12*\n&DOWNLOAD_ACTIVITY_NAME_FAILED_DOWNLOAD\x10\x0b\x12-\n)DOWNLOAD_ACTIVITY_NAME_COMPLETED_DOWNLOAD\x10\x0c\x12*\n&DOWNLOAD_ACTIVITY_NAME_QUEUED_DOWNLOAD\x10\rB}\n-com.hotstar.event.model.client.download.modelP\x01ZJgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/download/modelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.download.model.download_activity_name_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n-com.hotstar.event.model.client.download.modelP\001ZJgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/download/model'
  _globals['_DOWNLOADACTIVITYNAME']._serialized_start=78
  _globals['_DOWNLOADACTIVITYNAME']._serialized_end=735
# @@protoc_insertion_point(module_scope)
