# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/download/model/download_activity_info.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/download/model/download_activity_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from client.download.model import download_activity_name_pb2 as client_dot_download_dot_model_dot_download__activity__name__pb2
from client.download.model import journey_type_pb2 as client_dot_download_dot_model_dot_journey__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2client/download/model/download_activity_info.proto\x12\x15\x63lient.download.model\x1a\x32\x63lient/download/model/download_activity_name.proto\x1a(client/download/model/journey_type.proto\"\xa7\x01\n\x14\x44ownloadActivityInfo\x12K\n\x16\x64ownload_activity_name\x18\x01 \x01(\x0e\x32+.client.download.model.DownloadActivityName\x12\x42\n\x16requested_journey_type\x18\x02 \x01(\x0e\x32\".client.download.model.JourneyTypeB}\n-com.hotstar.event.model.client.download.modelP\x01ZJgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/download/modelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.download.model.download_activity_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n-com.hotstar.event.model.client.download.modelP\001ZJgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/download/model'
  _globals['_DOWNLOADACTIVITYINFO']._serialized_start=172
  _globals['_DOWNLOADACTIVITYINFO']._serialized_end=339
# @@protoc_insertion_point(module_scope)
