# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v2/subcontrollers/download/download_get_status_request.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'v2/subcontrollers/download/download_get_status_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<v2/subcontrollers/download/download_get_status_request.proto\x12\x10\x66\x65\x61ture.download\"@\n\x15\x44ownloadStatusRequest\x12\x13\n\x0b\x64ownload_id\x18\x01 \x01(\t\x12\x12\n\nprofile_id\x18\x02 \x01(\tBg\n%com.hotstar.ui.model.feature.downloadP\x01Z<github.com/hotstar/hs-core-api-go/v2/subcontrollers/downloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v2.subcontrollers.download.download_get_status_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.hotstar.ui.model.feature.downloadP\001Z<github.com/hotstar/hs-core-api-go/v2/subcontrollers/download'
  _globals['_DOWNLOADSTATUSREQUEST']._serialized_start=82
  _globals['_DOWNLOADSTATUSREQUEST']._serialized_end=146
# @@protoc_insertion_point(module_scope)
