# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v2/subcontrollers/download/download_init_request.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'v2/subcontrollers/download/download_init_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6v2/subcontrollers/download/download_init_request.proto\x12\x10\x66\x65\x61ture.download\"\xbb\x04\n\x13\x44ownloadInitRequest\x12\x12\n\ncontent_id\x18\x01 \x01(\t\x12\x18\n\x10\x63ontent_provider\x18\x02 \x01(\t\x12\x12\n\nis_premium\x18\x03 \x01(\x08\x12\x11\n\tstudio_id\x18\x04 \x01(\t\x12\x13\n\x0bstudio_name\x18\x05 \x01(\t\x12\x12\n\ntitle_name\x18\x06 \x01(\t\x12\x1b\n\x13\x63lient_capabilities\x18\x08 \x01(\t\x12\x15\n\rdrm_parameter\x18\t \x01(\t\x12\x16\n\x0e\x61\x64vertising_id\x18\n \x01(\t\x12\x19\n\x11\x63lient_request_id\x18\x0b \x01(\t\x12\x10\n\x08user_lat\x18\x0c \x01(\t\x12\x14\n\x0c\x64\x65vice_brand\x18\r \x01(\t\x12\x14\n\x0c\x64\x65vice_model\x18\x0e \x01(\t\x12\x16\n\x0e\x64\x65vice_carrier\x18\x0f \x01(\t\x12\x19\n\x11\x64\x65vice_os_version\x18\x10 \x01(\t\x12\x1b\n\x13\x64\x65vice_network_data\x18\x11 \x01(\t\x12\x17\n\x0f\x64\x65vice_platform\x18\x12 \x01(\t\x12\x1a\n\x12\x64\x65vice_app_version\x18\x13 \x01(\t\x12\x18\n\x10\x63ontent_language\x18\x14 \x01(\t\x12\x13\n\x0b\x63ustom_tags\x18\x15 \x01(\t\x12\x14\n\x0c\x64ownload_ids\x18\x16 \x03(\t\x12!\n\x19preferred_audio_languages\x18\x17 \x03(\t\x12\x14\n\x0c\x63ontent_type\x18\x18 \x01(\tBg\n%com.hotstar.ui.model.feature.downloadP\x01Z<github.com/hotstar/hs-core-api-go/v2/subcontrollers/downloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v2.subcontrollers.download.download_init_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.hotstar.ui.model.feature.downloadP\001Z<github.com/hotstar/hs-core-api-go/v2/subcontrollers/download'
  _globals['_DOWNLOADINITREQUEST']._serialized_start=77
  _globals['_DOWNLOADINITREQUEST']._serialized_end=648
# @@protoc_insertion_point(module_scope)
