# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/inapp_rating_triggered.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/inapp_rating_triggered.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#client/inapp_rating_triggered.proto\x12\x06\x63lient\"\x84\x01\n\x14InappRatingTriggered\x12%\n\x06source\x18\x01 \x01(\x0e\x32\x15.client.TriggerSource\x12\x18\n\x0csession_time\x18\x02 \x01(\tB\x02\x18\x01\x12\x11\n\tis_repeat\x18\x03 \x01(\x08\x12\x18\n\x10\x61pp_session_time\x18\x04 \x01(\x03*n\n\rTriggerSource\x12\x1e\n\x1aTRIGGER_SOURCE_UNSPECIFIED\x10\x00\x12\"\n\x1eTRIGGER_SOURCE_END_OF_PLAYBACK\x10\x01\x12\x19\n\x15TRIGGER_SOURCE_BROWSE\x10\x02\x42_\n\x1e\x63om.hotstar.event.model.clientP\x01Z;github.com/hotstar/data-event-schemas-go/hsanalytics/clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.inapp_rating_triggered_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.hotstar.event.model.clientP\001Z;github.com/hotstar/data-event-schemas-go/hsanalytics/client'
  _globals['_INAPPRATINGTRIGGERED'].fields_by_name['session_time']._loaded_options = None
  _globals['_INAPPRATINGTRIGGERED'].fields_by_name['session_time']._serialized_options = b'\030\001'
  _globals['_TRIGGERSOURCE']._serialized_start=182
  _globals['_TRIGGERSOURCE']._serialized_end=292
  _globals['_INAPPRATINGTRIGGERED']._serialized_start=48
  _globals['_INAPPRATINGTRIGGERED']._serialized_end=180
# @@protoc_insertion_point(module_scope)
