# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/tray_interaction.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/tray_interaction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x63lient/tray_interaction.proto\x12\x06\x63lient\"\x99\x04\n\x19TrayInteractionProperties\x12X\n\x17tray_interaction_effect\x18\x01 \x01(\x0e\x32\x37.client.TrayInteractionProperties.TrayInteractionEffect\x12\x63\n\x1dtray_interaction_trigger_type\x18\x02 \x01(\x0e\x32<.client.TrayInteractionProperties.TrayInteractionTriggerType\"\x90\x01\n\x15TrayInteractionEffect\x12\'\n#TRAY_INTERACTION_EFFECT_UNSPECIFIED\x10\x00\x12%\n!TRAY_INTERACTION_EFFECT_COLLAPSED\x10\x01\x12\'\n#TRAY_INTERACTION_EFFECT_UNCOLLAPSED\x10\x02\"\xa9\x01\n\x1aTrayInteractionTriggerType\x12-\n)TRAY_INTERACTION_TRIGGER_TYPE_UNSPECIFIED\x10\x00\x12-\n)TRAY_INTERACTION_TRIGGER_TYPE_CLICK_CARET\x10\x01\x12-\n)TRAY_INTERACTION_TRIGGER_TYPE_TAP_OUTSIDE\x10\x02\x42_\n\x1e\x63om.hotstar.event.model.clientP\x01Z;github.com/hotstar/data-event-schemas-go/hsanalytics/clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.tray_interaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.hotstar.event.model.clientP\001Z;github.com/hotstar/data-event-schemas-go/hsanalytics/client'
  _globals['_TRAYINTERACTIONPROPERTIES']._serialized_start=42
  _globals['_TRAYINTERACTIONPROPERTIES']._serialized_end=579
  _globals['_TRAYINTERACTIONPROPERTIES_TRAYINTERACTIONEFFECT']._serialized_start=263
  _globals['_TRAYINTERACTIONPROPERTIES_TRAYINTERACTIONEFFECT']._serialized_end=407
  _globals['_TRAYINTERACTIONPROPERTIES_TRAYINTERACTIONTRIGGERTYPE']._serialized_start=410
  _globals['_TRAYINTERACTIONPROPERTIES_TRAYINTERACTIONTRIGGERTYPE']._serialized_end=579
# @@protoc_insertion_point(module_scope)
