# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/widget_position.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/widget_position.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63lient/widget_position.proto\x12\x06\x63lient\"@\n\x0eWidgetPosition\x12\x17\n\x0fwidget_position\x18\x01 \x01(\x05\x12\x15\n\rtile_position\x18\x02 \x01(\x05\x42_\n\x1e\x63om.hotstar.event.model.clientP\x01Z;github.com/hotstar/data-event-schemas-go/hsanalytics/clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.widget_position_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.hotstar.event.model.clientP\001Z;github.com/hotstar/data-event-schemas-go/hsanalytics/client'
  _globals['_WIDGETPOSITION']._serialized_start=40
  _globals['_WIDGETPOSITION']._serialized_end=104
# @@protoc_insertion_point(module_scope)
