# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feature/color/color.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'feature/color/color.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from composable.tokens import dls_tokens_pb2 as composable_dot_tokens_dot_dls__tokens__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66\x65\x61ture/color/color.proto\x12\rfeature.color\x1a\"composable/tokens/dls_tokens.proto\"V\n\x05\x43olor\x12\x12\n\x08hex_code\x18\x01 \x01(\tH\x00\x12\x31\n\tdls_color\x18\x02 \x01(\x0e\x32\x1c.composable.tokens.DLSColorsH\x00\x42\x06\n\x04\x64\x61taB7Z5github.com/hotstar/hs-core-ui-models-go/feature/colorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feature.color.color_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/hotstar/hs-core-ui-models-go/feature/color'
  _globals['_COLOR']._serialized_start=80
  _globals['_COLOR']._serialized_end=166
# @@protoc_insertion_point(module_scope)
