# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/preload/cache_perf_properties.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/preload/cache_perf_properties.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*client/preload/cache_perf_properties.proto\x12\x0e\x63lient.preload\"\x96\x01\n\x14\x43\x61\x63heWriteProperties\x12\x30\n\x06\x63ommon\x18\x01 \x01(\x0b\x32 .client.preload.CacheCommonModel\x12\x17\n\x0f\x64\x65leted_entries\x18\x02 \x01(\x05\x12\x1d\n\x15\x64\x65leted_size_in_bytes\x18\x03 \x01(\x03\x12\x14\n\x0cis_discarded\x18\x04 \x01(\x08\"F\n\x12\x43\x61\x63heHitProperties\x12\x30\n\x06\x63ommon\x18\x01 \x01(\x0b\x32 .client.preload.CacheCommonModel\"|\n\x15\x43\x61\x63heDeleteProperties\x12\x30\n\x06\x63ommon\x18\x01 \x01(\x0b\x32 .client.preload.CacheCommonModel\x12\x31\n\x06reason\x18\x02 \x01(\x0e\x32!.client.preload.CacheDeleteReason\"G\n\x14\x43\x61\x63heClearProperties\x12/\n\x05items\x18\x01 \x03(\x0b\x32 .client.preload.CacheCommonModel\"\x9b\x01\n\x10\x43\x61\x63heCommonModel\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12\x38\n\rexpiry_policy\x18\x02 \x01(\x0e\x32!.client.preload.CacheExpiryPolicy\x12\x0f\n\x07max_age\x18\x03 \x01(\x03\x12\x15\n\rsize_in_bytes\x18\x04 \x01(\x03\x12\x11\n\tcache_key\x18\x05 \x01(\t*\xa0\x01\n\x11\x43\x61\x63heExpiryPolicy\x12#\n\x1f\x43\x41\x43HE_EXPIRY_POLICY_UNSPECIFIED\x10\x00\x12\x1e\n\x1a\x43\x41\x43HE_EXPIRY_POLICY_ACCESS\x10\x01\x12\x1f\n\x1b\x43\x41\x43HE_EXPIRY_POLICY_SESSION\x10\x02\x12%\n!CACHE_EXPIRY_POLICY_CROSS_SESSION\x10\x03*\x9f\x01\n\x11\x43\x61\x63heDeleteReason\x12#\n\x1f\x43\x41\x43HE_DELETE_REASON_UNSPECIFIED\x10\x00\x12\x1f\n\x1b\x43\x41\x43HE_DELETE_REASON_EXPIRED\x10\x01\x12\x1f\n\x1b\x43\x41\x43HE_DELETE_REASON_VACATED\x10\x02\x12#\n\x1f\x43\x41\x43HE_DELETE_REASON_INVALIDATED\x10\x03\x42o\n&com.hotstar.event.model.client.preloadP\x01ZCgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/preloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.preload.cache_perf_properties_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n&com.hotstar.event.model.client.preloadP\001ZCgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/preload'
  _globals['_CACHEEXPIRYPOLICY']._serialized_start=645
  _globals['_CACHEEXPIRYPOLICY']._serialized_end=805
  _globals['_CACHEDELETEREASON']._serialized_start=808
  _globals['_CACHEDELETEREASON']._serialized_end=967
  _globals['_CACHEWRITEPROPERTIES']._serialized_start=63
  _globals['_CACHEWRITEPROPERTIES']._serialized_end=213
  _globals['_CACHEHITPROPERTIES']._serialized_start=215
  _globals['_CACHEHITPROPERTIES']._serialized_end=285
  _globals['_CACHEDELETEPROPERTIES']._serialized_start=287
  _globals['_CACHEDELETEPROPERTIES']._serialized_end=411
  _globals['_CACHECLEARPROPERTIES']._serialized_start=413
  _globals['_CACHECLEARPROPERTIES']._serialized_end=484
  _globals['_CACHECOMMONMODEL']._serialized_start=487
  _globals['_CACHECOMMONMODEL']._serialized_end=642
# @@protoc_insertion_point(module_scope)
