# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spacedata/story.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'spacedata/story.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import space_data_commons_pb2 as base_dot_space__data__commons__pb2
from feature.header import story_header_pb2 as feature_dot_header_dot_story__header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15spacedata/story.proto\x12\tspacedata\x1a\x1d\x62\x61se/space_data_commons.proto\x1a!feature/header/story_header.proto\"\xf1\x01\n\x0eStorySpaceData\x12\x32\n\x12space_data_commons\x18\x01 \x01(\x0b\x32\x16.base.SpaceDataCommons\x12\x39\n\x0bheader_type\x18\x02 \x01(\x0e\x32$.spacedata.StorySpaceData.HeaderType\x12;\n\x0estories_config\x18\x03 \x01(\x0b\x32!.feature.header.StoryHeaderConfigH\x00\")\n\nHeaderType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\n\n\x06SLIDER\x10\x01\x42\x08\n\x06\x63onfigBU\n\x1e\x63om.hotstar.ui.model.spacedataP\x01Z1github.com/hotstar/hs-core-ui-models-go/spacedatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spacedata.story_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.hotstar.ui.model.spacedataP\001Z1github.com/hotstar/hs-core-ui-models-go/spacedata'
  _globals['_STORYSPACEDATA']._serialized_start=103
  _globals['_STORYSPACEDATA']._serialized_end=344
  _globals['_STORYSPACEDATA_HEADERTYPE']._serialized_start=293
  _globals['_STORYSPACEDATA_HEADERTYPE']._serialized_end=334
# @@protoc_insertion_point(module_scope)
