# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feature/image/screen_size_image.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'feature/image/screen_size_image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from feature.image import image_pb2 as feature_dot_image_dot_image__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%feature/image/screen_size_image.proto\x12\rfeature.image\x1a\x19\x66\x65\x61ture/image/image.proto\"\xc4\x01\n\x0fScreenSizeImage\x12)\n\x0bsmall_image\x18\x01 \x01(\x0b\x32\x14.feature.image.Image\x12*\n\x0cmedium_image\x18\x02 \x01(\x0b\x32\x14.feature.image.Image\x12)\n\x0blarge_image\x18\x03 \x01(\x0b\x32\x14.feature.image.Image\x12/\n\x11\x65xtra_large_image\x18\x04 \x01(\x0b\x32\x14.feature.image.ImageB]\n\"com.hotstar.ui.model.feature.imageP\x01Z5github.com/hotstar/hs-core-ui-models-go/feature/imageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feature.image.screen_size_image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"com.hotstar.ui.model.feature.imageP\001Z5github.com/hotstar/hs-core-ui-models-go/feature/image'
  _globals['_SCREENSIZEIMAGE']._serialized_start=84
  _globals['_SCREENSIZEIMAGE']._serialized_end=280
# @@protoc_insertion_point(module_scope)
