# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: component/growth/clicked_item.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'component/growth/clicked_item.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#component/growth/clicked_item.proto\x12\x10\x63omponent.growth\"+\n\x15\x43lickedItemProperties\x12\x12\n\nidentifier\x18\x01 \x01(\tBl\n!com.hotstar.event.model.componentP\x01ZEgithub.com/hotstar/data-event-schemas-go/hsanalytics/component/growthb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'component.growth.clicked_item_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.hotstar.event.model.componentP\001ZEgithub.com/hotstar/data-event-schemas-go/hsanalytics/component/growth'
  _globals['_CLICKEDITEMPROPERTIES']._serialized_start=57
  _globals['_CLICKEDITEMPROPERTIES']._serialized_end=100
# @@protoc_insertion_point(module_scope)
