# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feature/payment/payment_gateway.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'feature/payment/payment_gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from feature.payment import init_payment_payload_pb2 as feature_dot_payment_dot_init__payment__payload__pb2
from feature.image import image_pb2 as feature_dot_image_dot_image__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%feature/payment/payment_gateway.proto\x12\x0f\x66\x65\x61ture.payment\x1a*feature/payment/init_payment_payload.proto\x1a\x19\x66\x65\x61ture/image/image.proto\"\x91\x05\n\x0ePaymentGateway\x12\x44\n\nprocessors\x18\x01 \x03(\x0b\x32\x30.feature.payment.PaymentGateway.PaymentProcessor\x1a\xd9\x01\n\x10PaymentProcessor\x12\x42\n\x04meta\x18\x01 \x01(\x0b\x32\x34.feature.payment.PaymentGateway.PaymentProcessorMeta\x12\x39\n\x0cinit_payload\x18\x02 \x01(\x0b\x32#.feature.payment.InitPaymentPayload\x12\x46\n\x19update_instrument_payload\x18\x03 \x01(\x0b\x32#.feature.payment.InitPaymentPayload\x1a\xdc\x02\n\x14PaymentProcessorMeta\x12\x0c\n\x04\x66low\x18\x01 \x01(\t\x12\x14\n\x08imageUrl\x18\x02 \x01(\tB\x02\x18\x01\x12\x1e\n\x16\x61pplicationPackageName\x18\x03 \x01(\t\x12\x0e\n\x06number\x18\x04 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x05 \x01(\t\x12#\n\x05image\x18\x06 \x01(\x0b\x32\x14.feature.image.Image\x12\r\n\x05label\x18\x07 \x01(\t\x12$\n\x1cstringified_app_click_action\x18\t \x01(\t\x12&\n\x1estringified_app_on_load_action\x18\n \x01(\t\x12\x16\n\x0euse_async_init\x18\x0b \x01(\x08\x12!\n\x19\x61uto_trigger_payment_init\x18\x0c \x01(\x08\x12\x13\n\x0bunavailable\x18\r \x01(\x08J\x04\x08\x08\x10\tR\x07\x61\x63tionsBa\n$com.hotstar.ui.model.feature.paymentP\x01Z7github.com/hotstar/hs-core-ui-models-go/feature/paymentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feature.payment.payment_gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.hotstar.ui.model.feature.paymentP\001Z7github.com/hotstar/hs-core-ui-models-go/feature/payment'
  _globals['_PAYMENTGATEWAY_PAYMENTPROCESSORMETA'].fields_by_name['imageUrl']._loaded_options = None
  _globals['_PAYMENTGATEWAY_PAYMENTPROCESSORMETA'].fields_by_name['imageUrl']._serialized_options = b'\030\001'
  _globals['_PAYMENTGATEWAY']._serialized_start=130
  _globals['_PAYMENTGATEWAY']._serialized_end=787
  _globals['_PAYMENTGATEWAY_PAYMENTPROCESSOR']._serialized_start=219
  _globals['_PAYMENTGATEWAY_PAYMENTPROCESSOR']._serialized_end=436
  _globals['_PAYMENTGATEWAY_PAYMENTPROCESSORMETA']._serialized_start=439
  _globals['_PAYMENTGATEWAY_PAYMENTPROCESSORMETA']._serialized_end=787
# @@protoc_insertion_point(module_scope)
