# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: component/core/track_prefetch_api_props.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'component/core/track_prefetch_api_props.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-component/core/track_prefetch_api_props.proto\x12\x0e\x63omponent.core\"\x97\x02\n\x15TrackPrefetchApiProps\x12<\n\x12prefetch_api_state\x18\x01 \x01(\x0e\x32 .component.core.PrefetchApiState\x12\x1a\n\x12prefetch_page_type\x18\x02 \x01(\t\x12\x1f\n\x17is_prefetch_api_allowed\x18\x03 \x01(\x08\x12!\n\x19is_prefetch_api_triggered\x18\x04 \x01(\x08\x12\x1c\n\x14\x63\x61\x63he_expiry_time_ms\x18\x05 \x01(\x03\x12\x1d\n\x15\x63\x61\x63he_created_time_ms\x18\x06 \x01(\x03\x12#\n\x1b\x63\x61\x63he_validity_left_time_ms\x18\x07 \x01(\x03*v\n\x10PrefetchApiState\x12\"\n\x1ePREFETCH_API_STATE_UNSPECIFIED\x10\x00\x12\x1e\n\x1aPREFETCH_API_STATE_SUCCESS\x10\x01\x12\x1e\n\x1aPREFETCH_API_STATE_FAILURE\x10\x02\x42o\n&com.hotstar.event.model.component.coreP\x01ZCgithub.com/hotstar/data-event-schemas-go/hsanalytics/component/coreb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'component.core.track_prefetch_api_props_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n&com.hotstar.event.model.component.coreP\001ZCgithub.com/hotstar/data-event-schemas-go/hsanalytics/component/core'
  _globals['_PREFETCHAPISTATE']._serialized_start=347
  _globals['_PREFETCHAPISTATE']._serialized_end=465
  _globals['_TRACKPREFETCHAPIPROPS']._serialized_start=66
  _globals['_TRACKPREFETCHAPIPROPS']._serialized_end=345
# @@protoc_insertion_point(module_scope)
