# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pagedata/quiz.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'pagedata/quiz.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import page_data_commons_pb2 as base_dot_page__data__commons__pb2
from feature.image import image_pb2 as feature_dot_image_dot_image__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13pagedata/quiz.proto\x12\x08pagedata\x1a\x1c\x62\x61se/page_data_commons.proto\x1a\x19\x66\x65\x61ture/image/image.proto\"\xbd\x02\n\x0cQuizPageData\x12\x30\n\x11page_data_commons\x18\x01 \x01(\x0b\x32\x15.base.PageDataCommons\x12\x36\n\tmeta_data\x18\x02 \x01(\x0b\x32#.pagedata.QuizPageData.QuizMetaData\x1a\xa2\x01\n\x0cQuizMetaData\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tseason_id\x18\x02 \x01(\t\x12\x10\n\x08round_id\x18\x03 \x01(\t\x12*\n\x0c\x62\x61\x63kdrop_img\x18\x04 \x01(\x0b\x32\x14.feature.image.Image\x12\x32\n\tpage_type\x18\x05 \x01(\x0e\x32\x1f.pagedata.QuizPageData.PageType\"\x1e\n\x08PageType\x12\x08\n\x04QUIZ\x10\x00\x12\x08\n\x04POLL\x10\x01\x42S\n\x1d\x63om.hotstar.ui.model.pagedataP\x01Z0github.com/hotstar/hs-core-ui-models-go/pagedatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pagedata.quiz_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.hotstar.ui.model.pagedataP\001Z0github.com/hotstar/hs-core-ui-models-go/pagedata'
  _globals['_QUIZPAGEDATA']._serialized_start=91
  _globals['_QUIZPAGEDATA']._serialized_end=408
  _globals['_QUIZPAGEDATA_QUIZMETADATA']._serialized_start=214
  _globals['_QUIZPAGEDATA_QUIZMETADATA']._serialized_end=376
  _globals['_QUIZPAGEDATA_PAGETYPE']._serialized_start=378
  _globals['_QUIZPAGEDATA_PAGETYPE']._serialized_end=408
# @@protoc_insertion_point(module_scope)
