# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: feature/motion_system/dynamic_visual_asset_name.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5feature/motion_system/dynamic_visual_asset_name.proto\x12\x15\x66\x65\x61ture.motion_system*\xa6\x02\n\x16\x44ynamicVisualAssetName\x12\x14\n\x10UNSPECIFIED_NAME\x10\x00\x12#\n\x1bSUBSSCRIBE_BUTTON_ANIMATION\x10\x01\x1a\x02\x08\x01\x12\x14\n\x10SKINNY_ANIMATION\x10\x02\x12/\n\'BILLBOARD_VIDEO_WITH_BREAKOUT_ANIMATION\x10\x03\x1a\x02\x08\x01\x12\x18\n\x14LIVE_BADGE_ANIMATION\x10\x04\x12\x16\n\x12\x46REE_CTA_ANIMATION\x10\x05\x12#\n\x1f\x43\x41TEGORIES_ONBOARDING_ANIMATION\x10\x06\x12\x13\n\x0f\x42ILLBOARD_VIDEO\x10\x07\x12\x1e\n\x1aSUBSCRIBE_BUTTON_ANIMATION\x10\x08\x42m\n*com.hotstar.ui.model.feature.motion_systemP\x01Z=github.com/hotstar/hs-core-ui-models-go/feature/motion_systemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feature.motion_system.dynamic_visual_asset_name_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n*com.hotstar.ui.model.feature.motion_systemP\001Z=github.com/hotstar/hs-core-ui-models-go/feature/motion_system'
  _DYNAMICVISUALASSETNAME.values_by_name["SUBSSCRIBE_BUTTON_ANIMATION"]._options = None
  _DYNAMICVISUALASSETNAME.values_by_name["SUBSSCRIBE_BUTTON_ANIMATION"]._serialized_options = b'\010\001'
  _DYNAMICVISUALASSETNAME.values_by_name["BILLBOARD_VIDEO_WITH_BREAKOUT_ANIMATION"]._options = None
  _DYNAMICVISUALASSETNAME.values_by_name["BILLBOARD_VIDEO_WITH_BREAKOUT_ANIMATION"]._serialized_options = b'\010\001'
  _globals['_DYNAMICVISUALASSETNAME']._serialized_start=81
  _globals['_DYNAMICVISUALASSETNAME']._serialized_end=375
# @@protoc_insertion_point(module_scope)
