# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/action_stack.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/action_stack.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import widget_commons_pb2 as base_dot_widget__commons__pb2
from composable.elements import button_tile_pb2 as composable_dot_elements_dot_button__tile__pb2
from composable.elements import button_tile_download_pb2 as composable_dot_elements_dot_button__tile__download__pb2
from composable.elements import button_tile_rating_pb2 as composable_dot_elements_dot_button__tile__rating__pb2
from composable.elements import button_tile_watchlist_pb2 as composable_dot_elements_dot_button__tile__watchlist__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19widget/action_stack.proto\x12\x06widget\x1a\x19\x62\x61se/widget_commons.proto\x1a%composable/elements/button_tile.proto\x1a.composable/elements/button_tile_download.proto\x1a,composable/elements/button_tile_rating.proto\x1a/composable/elements/button_tile_watchlist.proto\"\x94\x03\n\x11\x41\x63tionStackWidget\x12+\n\x0ewidget_commons\x18\x01 \x01(\x0b\x32\x13.base.WidgetCommons\x12,\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32\x1e.widget.ActionStackWidget.Data\x1a\x35\n\x04\x44\x61ta\x12-\n\x05tiles\x18\x01 \x03(\x0b\x32\x1e.widget.ActionStackWidget.Tile\x1a\xec\x01\n\x04Tile\x12-\n\x0btile_button\x18\x01 \x01(\x0b\x32\x16.composable.ButtonTileH\x00\x12\x39\n\x0f\x64ownload_button\x18\x02 \x01(\x0b\x32\x1e.composable.ButtonTileDownloadH\x00\x12;\n\x10watchlist_button\x18\x03 \x01(\x0b\x32\x1f.composable.ButtonTileWatchlistH\x00\x12\x35\n\rrating_button\x18\x04 \x01(\x0b\x32\x1c.composable.ButtonTileRatingH\x00\x42\x06\n\x04tileBO\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.action_stack_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_ACTIONSTACKWIDGET']._serialized_start=247
  _globals['_ACTIONSTACKWIDGET']._serialized_end=651
  _globals['_ACTIONSTACKWIDGET_DATA']._serialized_start=359
  _globals['_ACTIONSTACKWIDGET_DATA']._serialized_end=412
  _globals['_ACTIONSTACKWIDGET_TILE']._serialized_start=415
  _globals['_ACTIONSTACKWIDGET_TILE']._serialized_end=651
# @@protoc_insertion_point(module_scope)
