# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/browse_sheet_header.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/browse_sheet_header.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import template_pb2 as base_dot_template__pb2
from base import widget_commons_pb2 as base_dot_widget__commons__pb2
from base import actions_pb2 as base_dot_actions__pb2
from feature.image import image_pb2 as feature_dot_image_dot_image__pb2
from widget import hero_gec_pb2 as widget_dot_hero__gec__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n widget/browse_sheet_header.proto\x12\x06widget\x1a\x13\x62\x61se/template.proto\x1a\x19\x62\x61se/widget_commons.proto\x1a\x12\x62\x61se/actions.proto\x1a\x19\x66\x65\x61ture/image/image.proto\x1a\x15widget/hero_gec.proto\"\x8a\x02\n\x17\x42rowseSheetHeaderWidget\x12+\n\x0ewidget_commons\x18\x01 \x01(\x0b\x32\x13.base.WidgetCommons\x12\r\n\x05title\x18\x0b \x01(\t\x12*\n\x0ctitle_cutout\x18\x0c \x01(\x0b\x32\x14.feature.image.Image\x12=\n\x10superscript_tags\x18\r \x03(\x0b\x32#.widget.BrowseSheetHeaderWidget.Tag\x1a\x42\n\x03Tag\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x1e\n\x07\x61\x63tions\x18\x03 \x01(\x0b\x32\r.base.ActionsJ\x04\x08\x02\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.browse_sheet_header_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_BROWSESHEETHEADERWIDGET']._serialized_start=163
  _globals['_BROWSESHEETHEADERWIDGET']._serialized_end=429
  _globals['_BROWSESHEETHEADERWIDGET_TAG']._serialized_start=357
  _globals['_BROWSESHEETHEADERWIDGET_TAG']._serialized_end=423
# @@protoc_insertion_point(module_scope)
