# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/consent_container.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/consent_container.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import widget_commons_pb2 as base_dot_widget__commons__pb2
from widget import disclaimer_consent_pb2 as widget_dot_disclaimer__consent__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ewidget/consent_container.proto\x12\x06widget\x1a\x19\x62\x61se/widget_commons.proto\x1a\x1fwidget/disclaimer_consent.proto\"\xc3\x01\n\x16\x43onsentContainerWidget\x12+\n\x0ewidget_commons\x18\x01 \x01(\x0b\x32\x13.base.WidgetCommons\x12\x31\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32#.widget.ConsentContainerWidget.Data\x1a\x43\n\x04\x44\x61ta\x12;\n\x12\x64isclaimer_consent\x18\x01 \x01(\x0b\x32\x1f.widget.DisclaimerConsentWidgetJ\x04\x08\x02\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.consent_container_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_CONSENTCONTAINERWIDGET']._serialized_start=103
  _globals['_CONSENTCONTAINERWIDGET']._serialized_end=298
  _globals['_CONSENTCONTAINERWIDGET_DATA']._serialized_start=225
  _globals['_CONSENTCONTAINERWIDGET_DATA']._serialized_end=292
# @@protoc_insertion_point(module_scope)
