# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/cw_tray.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/cw_tray.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import template_pb2 as base_dot_template__pb2
from base import widget_commons_pb2 as base_dot_widget__commons__pb2
from base import actions_pb2 as base_dot_actions__pb2
from widget import cw_card_pb2 as widget_dot_cw__card__pb2
from widget import header_pb2 as widget_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14widget/cw_tray.proto\x12\x06widget\x1a\x13\x62\x61se/template.proto\x1a\x19\x62\x61se/widget_commons.proto\x1a\x12\x62\x61se/actions.proto\x1a\x14widget/cw_card.proto\x1a\x13widget/header.proto\"\xb7\x05\n\x0c\x43WTrayWidget\x12$\n\x08template\x18\x01 \x01(\x0b\x32\x0e.base.TemplateB\x02\x18\x01\x12+\n\x0ewidget_commons\x18\x02 \x01(\x0b\x32\x13.base.WidgetCommons\x12\'\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32\x19.widget.CWTrayWidget.Data\x1a\xf6\x01\n\x04\x44\x61ta\x12/\n\x06header\x18\x01 \x01(\x0b\x32\x1b.widget.CWTrayWidget.HeaderB\x02\x18\x01\x12(\n\x05items\x18\x03 \x03(\x0b\x32\x19.widget.CWTrayWidget.Item\x12\x18\n\x10next_cw_tray_url\x18\x04 \x01(\t\x12\x36\n\x0crefresh_info\x18\x05 \x01(\x0b\x32 .widget.CWTrayWidget.RefreshInfo\x12)\n\x0btray_header\x18\x06 \x01(\x0b\x32\x14.widget.HeaderWidgetJ\x04\x08\x02\x10\x03R\x10more_widgets_url\x1a\x36\n\x0bRefreshInfo\x12\x12\n\nmax_age_ms\x18\x01 \x01(\x03\x12\x13\n\x0brefresh_url\x18\x02 \x01(\t\x1ag\n\x06Header\x12\r\n\x05title\x18\x01 \x01(\t\x12\x1e\n\x07\x61\x63tions\x18\x02 \x01(\x0b\x32\r.base.Actions\x12.\n\x03\x63ta\x18\x03 \x01(\x0b\x32!.widget.CWTrayWidget.IconLabelCTA\x1a\x39\n\x04Item\x12\'\n\x07\x63w_card\x18\x01 \x01(\x0b\x32\x14.widget.CWCardWidgetH\x00\x42\x08\n\x06widget\x1aP\n\x0cIconLabelCTA\x12\r\n\x05label\x18\x01 \x01(\t\x12\x11\n\ticon_name\x18\x02 \x01(\t\x12\x1e\n\x07\x61\x63tions\x18\x03 \x01(\x0b\x32\r.base.ActionsJ\x04\x08\x03\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.cw_tray_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_CWTRAYWIDGET_DATA'].fields_by_name['header']._loaded_options = None
  _globals['_CWTRAYWIDGET_DATA'].fields_by_name['header']._serialized_options = b'\030\001'
  _globals['_CWTRAYWIDGET'].fields_by_name['template']._loaded_options = None
  _globals['_CWTRAYWIDGET'].fields_by_name['template']._serialized_options = b'\030\001'
  _globals['_CWTRAYWIDGET']._serialized_start=144
  _globals['_CWTRAYWIDGET']._serialized_end=839
  _globals['_CWTRAYWIDGET_DATA']._serialized_start=285
  _globals['_CWTRAYWIDGET_DATA']._serialized_end=531
  _globals['_CWTRAYWIDGET_REFRESHINFO']._serialized_start=533
  _globals['_CWTRAYWIDGET_REFRESHINFO']._serialized_end=587
  _globals['_CWTRAYWIDGET_HEADER']._serialized_start=589
  _globals['_CWTRAYWIDGET_HEADER']._serialized_end=692
  _globals['_CWTRAYWIDGET_ITEM']._serialized_start=694
  _globals['_CWTRAYWIDGET_ITEM']._serialized_end=751
  _globals['_CWTRAYWIDGET_ICONLABELCTA']._serialized_start=753
  _globals['_CWTRAYWIDGET_ICONLABELCTA']._serialized_end=833
# @@protoc_insertion_point(module_scope)
