# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/display_ad_container.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/display_ad_container.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import widget_commons_pb2 as base_dot_widget__commons__pb2
from widget import image_display_ad_pb2 as widget_dot_image__display__ad__pb2
from widget import video_display_ad_pb2 as widget_dot_video__display__ad__pb2
from widget import no_fill_ad_pb2 as widget_dot_no__fill__ad__pb2
from widget import carousel_display_ad_pb2 as widget_dot_carousel__display__ad__pb2
from widget import lottie_banner_pb2 as widget_dot_lottie__banner__pb2
from feature.refresh import refresh_info_pb2 as feature_dot_refresh_dot_refresh__info__pb2
from feature.image import aspect_ratio_pb2 as feature_dot_image_dot_aspect__ratio__pb2
from widget import video_quality_comparator_pb2 as widget_dot_video__quality__comparator__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!widget/display_ad_container.proto\x12\x06widget\x1a\x19\x62\x61se/widget_commons.proto\x1a\x1dwidget/image_display_ad.proto\x1a\x1dwidget/video_display_ad.proto\x1a\x17widget/no_fill_ad.proto\x1a widget/carousel_display_ad.proto\x1a\x1awidget/lottie_banner.proto\x1a\"feature/refresh/refresh_info.proto\x1a feature/image/aspect_ratio.proto\x1a%widget/video_quality_comparator.proto\"\xfe\x05\n\x18\x44isplayAdContainerWidget\x12+\n\x0ewidget_commons\x18\x01 \x01(\x0b\x32\x13.base.WidgetCommons\x12\x33\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32%.widget.DisplayAdContainerWidget.Data\x1a\x9b\x04\n\x04\x44\x61ta\x12\x32\n\x0crefresh_info\x18\x01 \x01(\x0b\x32\x1c.feature.refresh.RefreshInfo\x12\x13\n\x0b\x61uto_invoke\x18\x08 \x01(\x08\x12\x1a\n\x12poll_limit_reached\x18\n \x01(\x08\x12\x30\n\x08image_ad\x18\x02 \x01(\x0b\x32\x1c.widget.ImageDisplayAdWidgetH\x00\x12,\n\nno_fill_ad\x18\x03 \x01(\x0b\x32\x16.widget.NoFillAdWidgetH\x00\x12/\n\tskinny_ad\x18\x04 \x01(\x0b\x32\x1a.widget.LottieBannerWidgetH\x00\x12\x36\n\x0b\x63\x61rousel_ad\x18\x05 \x01(\x0b\x32\x1f.widget.CarouselDisplayAdWidgetH\x00\x12W\n\x16\x64isplay_ad_placeholder\x18\x06 \x01(\x0b\x32\x35.widget.DisplayAdContainerWidget.DisplayAdPlaceholderH\x00\x12\x30\n\x08video_ad\x18\x07 \x01(\x0b\x32\x1c.widget.VideoDisplayAdWidgetH\x00\x12L\n\x18video_quality_comparator\x18\t \x01(\x0b\x32$.widget.VideoQualityComparatorWidgetB\x02\x18\x01H\x00\x42\x0c\n\ndisplay_ad\x1a\\\n\x14\x44isplayAdPlaceholder\x12\x12\n\nwidget_url\x18\x01 \x01(\t\x12\x30\n\x0c\x61spect_ratio\x18\x02 \x01(\x0b\x32\x1a.feature.image.AspectRatioJ\x04\x08\x02\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.display_ad_container_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_DISPLAYADCONTAINERWIDGET_DATA'].fields_by_name['video_quality_comparator']._loaded_options = None
  _globals['_DISPLAYADCONTAINERWIDGET_DATA'].fields_by_name['video_quality_comparator']._serialized_options = b'\030\001'
  _globals['_DISPLAYADCONTAINERWIDGET']._serialized_start=331
  _globals['_DISPLAYADCONTAINERWIDGET']._serialized_end=1097
  _globals['_DISPLAYADCONTAINERWIDGET_DATA']._serialized_start=458
  _globals['_DISPLAYADCONTAINERWIDGET_DATA']._serialized_end=997
  _globals['_DISPLAYADCONTAINERWIDGET_DISPLAYADPLACEHOLDER']._serialized_start=999
  _globals['_DISPLAYADCONTAINERWIDGET_DISPLAYADPLACEHOLDER']._serialized_end=1091
# @@protoc_insertion_point(module_scope)
