# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/download_status.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/download_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from feature.download import download_content_state_pb2 as feature_dot_download_dot_download__content__state__pb2
from base import actions_pb2 as base_dot_actions__pb2
from base import widget_commons_pb2 as base_dot_widget__commons__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cwidget/download_status.proto\x12\x06widget\x1a-feature/download/download_content_state.proto\x1a\x12\x62\x61se/actions.proto\x1a\x19\x62\x61se/widget_commons.proto\"\xb9\x07\n\x14\x44ownloadStatusWidget\x12+\n\x0ewidget_commons\x18\x01 \x01(\x0b\x32\x13.base.WidgetCommons\x12I\n\x12user_facing_action\x18\x0b \x01(\x0b\x32-.widget.DownloadStatusWidget.UserFacingAction\x12<\n\x0c\x63ontentState\x18\x0c \x01(\x0b\x32&.feature.download.DownloadContentState\x1a\x96\x01\n\x10UserFacingAction\x12?\n\x04type\x18\x01 \x01(\x0e\x32\x31.widget.DownloadStatusWidget.UserFacingActionType\x12\x41\n\x05value\x18\x02 \x01(\x0b\x32\x32.widget.DownloadStatusWidget.UserFacingActionValue\x1a\xba\x01\n\x15UserFacingActionValue\x12 \n\x07\x61\x63tions\x18\x01 \x01(\x0b\x32\r.base.ActionsH\x00\x12\x37\n\x05toast\x18\x02 \x01(\x0b\x32&.widget.DownloadStatusWidget.ShowToastH\x00\x12=\n\x05\x61lert\x18\x03 \x01(\x0b\x32,.widget.DownloadStatusWidget.ShowActionSheetH\x00\x42\x07\n\x05value\x1a\x19\n\tShowToast\x12\x0c\n\x04text\x18\x01 \x01(\t\x1a\x9d\x01\n\x0fShowActionSheet\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\t\x12\x35\n\x0bprimary_cta\x18\x03 \x01(\x0b\x32 .widget.DownloadStatusWidget.CTA\x12\x37\n\rsecondary_cta\x18\x04 \x01(\x0b\x32 .widget.DownloadStatusWidget.CTA\x1ah\n\x03\x43TA\x12\r\n\x05title\x18\x01 \x01(\t\x12\x32\n\x04type\x18\x02 \x01(\x0e\x32$.widget.DownloadStatusWidget.CTAType\x12\x1e\n\x07\x61\x63tions\x18\x03 \x01(\x0b\x32\r.base.Actions\"F\n\x14UserFacingActionType\x12\x0e\n\nBFF_ACTION\x10\x00\x12\x0e\n\nSHOW_TOAST\x10\x01\x12\x0e\n\nSHOW_SHEET\x10\x02\"\"\n\x07\x43TAType\x12\x0b\n\x07\x44ISMISS\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01J\x04\x08\x02\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.download_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_DOWNLOADSTATUSWIDGET']._serialized_start=135
  _globals['_DOWNLOADSTATUSWIDGET']._serialized_end=1088
  _globals['_DOWNLOADSTATUSWIDGET_USERFACINGACTION']._serialized_start=342
  _globals['_DOWNLOADSTATUSWIDGET_USERFACINGACTION']._serialized_end=492
  _globals['_DOWNLOADSTATUSWIDGET_USERFACINGACTIONVALUE']._serialized_start=495
  _globals['_DOWNLOADSTATUSWIDGET_USERFACINGACTIONVALUE']._serialized_end=681
  _globals['_DOWNLOADSTATUSWIDGET_SHOWTOAST']._serialized_start=683
  _globals['_DOWNLOADSTATUSWIDGET_SHOWTOAST']._serialized_end=708
  _globals['_DOWNLOADSTATUSWIDGET_SHOWACTIONSHEET']._serialized_start=711
  _globals['_DOWNLOADSTATUSWIDGET_SHOWACTIONSHEET']._serialized_end=868
  _globals['_DOWNLOADSTATUSWIDGET_CTA']._serialized_start=870
  _globals['_DOWNLOADSTATUSWIDGET_CTA']._serialized_end=974
  _globals['_DOWNLOADSTATUSWIDGET_USERFACINGACTIONTYPE']._serialized_start=976
  _globals['_DOWNLOADSTATUSWIDGET_USERFACINGACTIONTYPE']._serialized_end=1046
  _globals['_DOWNLOADSTATUSWIDGET_CTATYPE']._serialized_start=1048
  _globals['_DOWNLOADSTATUSWIDGET_CTATYPE']._serialized_end=1082
# @@protoc_insertion_point(module_scope)
