# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/email_capture.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/email_capture.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import widget_commons_pb2 as base_dot_widget__commons__pb2
from base import actions_pb2 as base_dot_actions__pb2
from feature.consent import consent_type_pb2 as feature_dot_consent_dot_consent__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1awidget/email_capture.proto\x12\x06widget\x1a\x19\x62\x61se/widget_commons.proto\x1a\x12\x62\x61se/actions.proto\x1a\"feature/consent/consent_type.proto\"\xdf\x05\n\x12\x45mailCaptureWidget\x12+\n\x0ewidget_commons\x18\x01 \x01(\x0b\x32\x13.base.WidgetCommons\x12-\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32\x1f.widget.EmailCaptureWidget.Data\x1a\xe7\x03\n\x04\x44\x61ta\x12\x11\n\tstep_name\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0binput_label\x18\x03 \x01(\t\x12\x13\n\x0bplaceholder\x18\x04 \x01(\t\x12\x13\n\x0b\x65mail_regex\x18\x05 \x01(\t\x12\x1b\n\x13regex_error_message\x18\x06 \x01(\t\x12\x15\n\rerror_message\x18\x07 \x01(\t\x12\x41\n\x0fsend_otp_button\x18\x08 \x01(\x0b\x32(.widget.EmailCaptureWidget.SendOtpButton\x12\x14\n\x0c\x63onsent_text\x18\x0c \x01(\t\x12@\n\x0e\x63onsent_status\x18\r \x01(\x0e\x32(.widget.EmailCaptureWidget.ConsentStatus\x12\x15\n\remail_address\x18\x0e \x01(\t\x12\x1c\n\x14password_input_label\x18\x0f \x01(\t\x12\x1c\n\x14password_placeholder\x18\x10 \x01(\t\x12\x16\n\x0epassword_regex\x18\x11 \x01(\t\x12\x1e\n\x16password_error_message\x18\x12 \x01(\t\x12$\n\x1cpassword_regex_error_message\x18\x13 \x01(\t\x1a=\n\rSendOtpButton\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x1e\n\x07\x61\x63tions\x18\x02 \x01(\x0b\x32\r.base.Actions\">\n\rConsentStatus\x12\x0b\n\x07OPT_OUT\x10\x00\x12\n\n\x06OPT_IN\x10\x01\x12\x14\n\x10\x41LREADY_OPTED_IN\x10\x02J\x04\x08\x02\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.email_capture_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_EMAILCAPTUREWIDGET']._serialized_start=122
  _globals['_EMAILCAPTUREWIDGET']._serialized_end=857
  _globals['_EMAILCAPTUREWIDGET_DATA']._serialized_start=237
  _globals['_EMAILCAPTUREWIDGET_DATA']._serialized_end=724
  _globals['_EMAILCAPTUREWIDGET_SENDOTPBUTTON']._serialized_start=726
  _globals['_EMAILCAPTUREWIDGET_SENDOTPBUTTON']._serialized_end=787
  _globals['_EMAILCAPTUREWIDGET_CONSENTSTATUS']._serialized_start=789
  _globals['_EMAILCAPTUREWIDGET_CONSENTSTATUS']._serialized_end=851
# @@protoc_insertion_point(module_scope)
