# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/mobile_detail.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/mobile_detail.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import widget_commons_pb2 as base_dot_widget__commons__pb2
from base import actions_pb2 as base_dot_actions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1awidget/mobile_detail.proto\x12\x06widget\x1a\x19\x62\x61se/widget_commons.proto\x1a\x12\x62\x61se/actions.proto\"\xb3\x02\n\x12MobileDetailWidget\x12+\n\x0ewidget_commons\x18\x01 \x01(\x0b\x32\x13.base.WidgetCommons\x12-\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32\x1f.widget.MobileDetailWidget.Data\x1at\n\x04\x44\x61ta\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x15\n\rmobile_number\x18\x02 \x01(\t\x12\x45\n\x0b\x65\x64it_button\x18\x03 \x01(\x0b\x32\x30.widget.MobileDetailWidget.EditPhoneNumberButton\x1a\x45\n\x15\x45\x64itPhoneNumberButton\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x1e\n\x07\x61\x63tions\x18\x02 \x01(\x0b\x32\r.base.ActionsJ\x04\x08\x02\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.modal.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.mobile_detail_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.modal.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_MOBILEDETAILWIDGET']._serialized_start=86
  _globals['_MOBILEDETAILWIDGET']._serialized_end=393
  _globals['_MOBILEDETAILWIDGET_DATA']._serialized_start=200
  _globals['_MOBILEDETAILWIDGET_DATA']._serialized_end=316
  _globals['_MOBILEDETAILWIDGET_EDITPHONENUMBERBUTTON']._serialized_start=318
  _globals['_MOBILEDETAILWIDGET_EDITPHONENUMBERBUTTON']._serialized_end=387
# @@protoc_insertion_point(module_scope)
