# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/parental_control_settings.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/parental_control_settings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import widget_commons_pb2 as base_dot_widget__commons__pb2
from base import actions_pb2 as base_dot_actions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&widget/parental_control_settings.proto\x12\x06widget\x1a\x19\x62\x61se/widget_commons.proto\x1a\x12\x62\x61se/actions.proto\"\xc9\x06\n\x1dParentalControlSettingsWidget\x12+\n\x0ewidget_commons\x18\x01 \x01(\x0b\x32\x13.base.WidgetCommons\x12\x38\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32*.widget.ParentalControlSettingsWidget.Data\x1a\xcc\x02\n\x04\x44\x61ta\x12J\n\rparental_lock\x18\x01 \x01(\x0b\x32\x33.widget.ParentalControlSettingsWidget.ToggleSetting\x12T\n\x14viewing_restrictions\x18\x02 \x01(\x0b\x32\x36.widget.ParentalControlSettingsWidget.ClickableSetting\x12X\n\x18\x63hange_parental_lock_pin\x18\x03 \x01(\x0b\x32\x36.widget.ParentalControlSettingsWidget.ClickableSetting\x12\r\n\x05title\x18\x04 \x01(\t\x12\x1e\n\x07\x61\x63tions\x18\x05 \x01(\x0b\x32\r.base.Actions\x12\x19\n\x11recaptcha_enabled\x18\x06 \x01(\x08\x1a\x93\x02\n\rToggleSetting\x12\x11\n\ticon_name\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x13\n\x0bis_selected\x18\x05 \x01(\x08\x12\"\n\x07\x61\x63tions\x18\x06 \x01(\x0b\x32\r.base.ActionsB\x02\x18\x01\x12\x14\n\x0cstatus_label\x18\x07 \x01(\t\x12\x15\n\renabled_label\x18\x08 \x01(\t\x12\x16\n\x0e\x64isabled_label\x18\t \x01(\t\x12&\n\x0fturn_off_action\x18\n \x01(\x0b\x32\r.base.Actions\x12%\n\x0eturn_on_action\x18\x0b \x01(\x0b\x32\r.base.Actions\x1aV\n\x10\x43lickableSetting\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x1e\n\x07\x61\x63tions\x18\x04 \x01(\x0b\x32\r.base.ActionsJ\x04\x08\x02\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.parental_control_settings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_PARENTALCONTROLSETTINGSWIDGET_TOGGLESETTING'].fields_by_name['actions']._loaded_options = None
  _globals['_PARENTALCONTROLSETTINGSWIDGET_TOGGLESETTING'].fields_by_name['actions']._serialized_options = b'\030\001'
  _globals['_PARENTALCONTROLSETTINGSWIDGET']._serialized_start=98
  _globals['_PARENTALCONTROLSETTINGSWIDGET']._serialized_end=939
  _globals['_PARENTALCONTROLSETTINGSWIDGET_DATA']._serialized_start=235
  _globals['_PARENTALCONTROLSETTINGSWIDGET_DATA']._serialized_end=567
  _globals['_PARENTALCONTROLSETTINGSWIDGET_TOGGLESETTING']._serialized_start=570
  _globals['_PARENTALCONTROLSETTINGSWIDGET_TOGGLESETTING']._serialized_end=845
  _globals['_PARENTALCONTROLSETTINGSWIDGET_CLICKABLESETTING']._serialized_start=847
  _globals['_PARENTALCONTROLSETTINGSWIDGET_CLICKABLESETTING']._serialized_end=933
# @@protoc_insertion_point(module_scope)
