# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/parental_lock_setup.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/parental_lock_setup.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import widget_commons_pb2 as base_dot_widget__commons__pb2
from base import actions_pb2 as base_dot_actions__pb2
from widget import verify_otp_pb2 as widget_dot_verify__otp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n widget/parental_lock_setup.proto\x12\x06widget\x1a\x19\x62\x61se/widget_commons.proto\x1a\x12\x62\x61se/actions.proto\x1a\x17widget/verify_otp.proto\"\xeb\x04\n\x17ParentalLockSetUpWidget\x12+\n\x0ewidget_commons\x18\x01 \x01(\x0b\x32\x13.base.WidgetCommons\x12\x32\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32$.widget.ParentalLockSetUpWidget.Data\x1a\x94\x02\n\x04\x44\x61ta\x12?\n\tenter_pin\x18\x01 \x01(\x0b\x32,.widget.ParentalLockSetUpWidget.ScreenLabels\x12\x41\n\x0b\x63onfirm_pin\x18\x02 \x01(\x0b\x32,.widget.ParentalLockSetUpWidget.ScreenLabels\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x10\n\x08pin_size\x18\x04 \x01(\x05\x12(\n\x11submit_pin_action\x18\x05 \x01(\x0b\x32\r.base.Actions\x12\r\n\x05title\x18\x06 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x07 \x01(\t\x12\x18\n\x10submit_pin_label\x18\x08 \x01(\t\x1a\x99\x01\n\x0cScreenLabels\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\t\x12\x18\n\x0c\x61\x63tion_label\x18\x03 \x01(\tB\x02\x18\x01\x12\x14\n\x0c\x63\x61ncel_label\x18\x04 \x01(\t\x12<\n\x0c\x63ontinue_btn\x18\x05 \x01(\x0b\x32&.widget.ParentalLockSetUpWidget.Button\x1a\x36\n\x06\x42utton\x12\r\n\x05label\x18\x01 \x01(\t\x12\x1d\n\x06\x61\x63tion\x18\x02 \x01(\x0b\x32\r.base.ActionsJ\x04\x08\x02\x10\x0b\x42\x30Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.parental_lock_setup_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_PARENTALLOCKSETUPWIDGET_SCREENLABELS'].fields_by_name['action_label']._loaded_options = None
  _globals['_PARENTALLOCKSETUPWIDGET_SCREENLABELS'].fields_by_name['action_label']._serialized_options = b'\030\001'
  _globals['_PARENTALLOCKSETUPWIDGET']._serialized_start=117
  _globals['_PARENTALLOCKSETUPWIDGET']._serialized_end=736
  _globals['_PARENTALLOCKSETUPWIDGET_DATA']._serialized_start=242
  _globals['_PARENTALLOCKSETUPWIDGET_DATA']._serialized_end=518
  _globals['_PARENTALLOCKSETUPWIDGET_SCREENLABELS']._serialized_start=521
  _globals['_PARENTALLOCKSETUPWIDGET_SCREENLABELS']._serialized_end=674
  _globals['_PARENTALLOCKSETUPWIDGET_BUTTON']._serialized_start=676
  _globals['_PARENTALLOCKSETUPWIDGET_BUTTON']._serialized_end=730
# @@protoc_insertion_point(module_scope)
