# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/payment_footer.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/payment_footer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import widget_commons_pb2 as base_dot_widget__commons__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bwidget/payment_footer.proto\x12\x06widget\x1a\x19\x62\x61se/widget_commons.proto\"\xe4\x02\n\x13PaymentFooterWidget\x12+\n\x0ewidget_commons\x18\x01 \x01(\x0b\x32\x13.base.WidgetCommons\x12.\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32 .widget.PaymentFooterWidget.Data\x1ai\n\x04\x44\x61ta\x12\x0c\n\x04icon\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08sub_text\x18\x03 \x01(\t\x12\x33\n\x07\x64\x65tails\x18\x04 \x03(\x0b\x32\".widget.PaymentFooterWidget.Detail\x1aN\n\x06\x44\x65tail\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12/\n\x05links\x18\x02 \x03(\x0b\x32 .widget.PaymentFooterWidget.Link\x1a/\n\x04Link\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\tJ\x04\x08\x02\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.payment_footer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_PAYMENTFOOTERWIDGET']._serialized_start=67
  _globals['_PAYMENTFOOTERWIDGET']._serialized_end=423
  _globals['_PAYMENTFOOTERWIDGET_DATA']._serialized_start=183
  _globals['_PAYMENTFOOTERWIDGET_DATA']._serialized_end=288
  _globals['_PAYMENTFOOTERWIDGET_DETAIL']._serialized_start=290
  _globals['_PAYMENTFOOTERWIDGET_DETAIL']._serialized_end=368
  _globals['_PAYMENTFOOTERWIDGET_LINK']._serialized_start=370
  _globals['_PAYMENTFOOTERWIDGET_LINK']._serialized_end=417
# @@protoc_insertion_point(module_scope)
