# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/payment_method_commons.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/payment_method_commons.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import actions_pb2 as base_dot_actions__pb2
from base import template_pb2 as base_dot_template__pb2
from base import widget_commons_pb2 as base_dot_widget__commons__pb2
from feature.image import image_pb2 as feature_dot_image_dot_image__pb2
from feature.payment import payment_gateway_pb2 as feature_dot_payment_dot_payment__gateway__pb2
from widget import text_list_pb2 as widget_dot_text__list__pb2
from widget import refreshable_status_pb2 as widget_dot_refreshable__status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#widget/payment_method_commons.proto\x12\x06widget\x1a\x12\x62\x61se/actions.proto\x1a\x13\x62\x61se/template.proto\x1a\x19\x62\x61se/widget_commons.proto\x1a\x19\x66\x65\x61ture/image/image.proto\x1a%feature/payment/payment_gateway.proto\x1a\x16widget/text_list.proto\x1a\x1fwidget/refreshable_status.proto\"\xa5\x05\n\x1aPaymentMethodCommonsWidget\x12+\n\x0ewidget_commons\x18\x01 \x01(\x0b\x32\x13.base.WidgetCommons\x12\x13\n\x0bmethod_name\x18\x02 \x01(\t\x12*\n\x0cmethod_image\x18\x03 \x01(\x0b\x32\x14.feature.image.Image\x12/\n\x0fmethod_features\x18\x04 \x01(\x0b\x32\x16.widget.TextListWidget\x12+\n\x0bmethod_info\x18\x05 \x01(\x0b\x32\x16.widget.TextListWidget\x12\x31\n\x08gateways\x18\x06 \x03(\x0b\x32\x1f.feature.payment.PaymentGateway\x12\x13\n\x0bis_expanded\x18\x07 \x01(\x08\x12S\n\x14selected_method_meta\x18\x08 \x01(\x0b\x32\x35.widget.PaymentMethodCommonsWidget.SelectedMethodMeta\x12\x45\n\x1cpayment_method_loading_state\x18\t \x01(\x0b\x32\x1f.widget.RefreshableStatusWidget\x12\x43\n\x1apayment_method_error_state\x18\n \x01(\x0b\x32\x1f.widget.RefreshableStatusWidget\x12.\n\x10tab_open_actions\x18\x0b \x03(\x0b\x32\x14.base.Actions.Action\x1a\x62\n\x12SelectedMethodMeta\x12\r\n\x05title\x18\x01 \x01(\t\x12\x1b\n\x13method_warning_text\x18\x02 \x01(\t\x12 \n\x18method_item_warning_text\x18\x03 \x01(\tBO\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.payment_method_commons_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_PAYMENTMETHODCOMMONSWIDGET']._serialized_start=239
  _globals['_PAYMENTMETHODCOMMONSWIDGET']._serialized_end=916
  _globals['_PAYMENTMETHODCOMMONSWIDGET_SELECTEDMETHODMETA']._serialized_start=818
  _globals['_PAYMENTMETHODCOMMONSWIDGET_SELECTEDMETHODMETA']._serialized_end=916
# @@protoc_insertion_point(module_scope)
