# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/pre_registration_container.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/pre_registration_container.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import widget_commons_pb2 as base_dot_widget__commons__pb2
from feature.branding import brand_pb2 as feature_dot_branding_dot_brand__pb2
from widget import logo_pb2 as widget_dot_logo__pb2
from widget import pre_registration_form_pb2 as widget_dot_pre__registration__form__pb2
from widget import verify_otp_pb2 as widget_dot_verify__otp__pb2
from widget import pre_registration_success_pb2 as widget_dot_pre__registration__success__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'widget/pre_registration_container.proto\x12\x06widget\x1a\x19\x62\x61se/widget_commons.proto\x1a\x1c\x66\x65\x61ture/branding/brand.proto\x1a\x11widget/logo.proto\x1a\"widget/pre_registration_form.proto\x1a\x17widget/verify_otp.proto\x1a%widget/pre_registration_success.proto\"\xa5\x04\n\x1ePreRegistrationContainerWidget\x12+\n\x0ewidget_commons\x18\x01 \x01(\x0b\x32\x13.base.WidgetCommons\x12\x39\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32+.widget.PreRegistrationContainerWidget.Data\x1a\xac\x01\n\x04\x44\x61ta\x12)\n\x04logo\x18\x01 \x01(\x0e\x32\x17.feature.branding.BrandB\x02\x18\x01\x12N\n\x07widgets\x18\x02 \x03(\x0b\x32=.widget.PreRegistrationContainerWidget.PreRegistrationWidgets\x12)\n\rbrand_details\x18\x03 \x01(\x0b\x32\x12.widget.LogoWidget\x1a\xe5\x01\n\x16PreRegistrationWidgets\x12\x42\n\x15pre_registration_form\x18\x01 \x01(\x0b\x32!.widget.PreRegistrationFormWidgetH\x00\x12-\n\nverify_otp\x18\x02 \x01(\x0b\x32\x17.widget.VerifyOtpWidgetH\x00\x12H\n\x18pre_registration_success\x18\x03 \x01(\x0b\x32$.widget.PreRegistrationSuccessWidgetH\x00\x42\x0e\n\x0c\x43hildWidgetsJ\x04\x08\x02\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.pre_registration_container_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_PREREGISTRATIONCONTAINERWIDGET_DATA'].fields_by_name['logo']._loaded_options = None
  _globals['_PREREGISTRATIONCONTAINERWIDGET_DATA'].fields_by_name['logo']._serialized_options = b'\030\001'
  _globals['_PREREGISTRATIONCONTAINERWIDGET']._serialized_start=228
  _globals['_PREREGISTRATIONCONTAINERWIDGET']._serialized_end=777
  _globals['_PREREGISTRATIONCONTAINERWIDGET_DATA']._serialized_start=367
  _globals['_PREREGISTRATIONCONTAINERWIDGET_DATA']._serialized_end=539
  _globals['_PREREGISTRATIONCONTAINERWIDGET_PREREGISTRATIONWIDGETS']._serialized_start=542
  _globals['_PREREGISTRATIONCONTAINERWIDGET_PREREGISTRATIONWIDGETS']._serialized_end=771
# @@protoc_insertion_point(module_scope)
