# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/profile_edit.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/profile_edit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import actions_pb2 as base_dot_actions__pb2
from base import widget_commons_pb2 as base_dot_widget__commons__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19widget/profile_edit.proto\x12\x06widget\x1a\x12\x62\x61se/actions.proto\x1a\x19\x62\x61se/widget_commons.proto\"\x98\x05\n\x11\x45\x64itProfileWidget\x12+\n\x0ewidget_commons\x18\x01 \x01(\x0b\x32\x13.base.WidgetCommons\x12,\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32\x1e.widget.EditProfileWidget.Data\x1a\xdf\x02\n\x04\x44\x61ta\x12\r\n\x05title\x18\x01 \x01(\t\x12\x17\n\x0fname_edit_label\x18\x02 \x01(\t\x12\x18\n\x0c\x64\x65lete_label\x18\x03 \x01(\tB\x02\x18\x01\x12\x19\n\rmaturity_text\x18\x04 \x01(\tB\x02\x18\x01\x12\x32\n\x0bsave_action\x18\x05 \x01(\x0b\x32\x1d.widget.EditProfileWidget.CTA\x12=\n\rdelete_option\x18\x06 \x01(\x0b\x32&.widget.EditProfileWidget.DeleteOption\x12\x18\n\x10name_input_regex\x18\x07 \x01(\t\x12\x31\n\ndelete_btn\x18\x08 \x01(\x0b\x32\x1d.widget.EditProfileWidget.CTA\x12!\n\x19invalid_name_user_message\x18\t \x01(\t\x12\x17\n\x0fname_max_length\x18\n \x01(\t\x1a\x89\x01\n\x0c\x44\x65leteOption\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\t\x12-\n\x06\x63\x61ncel\x18\x03 \x01(\x0b\x32\x1d.widget.EditProfileWidget.CTA\x12-\n\x06\x64\x65lete\x18\x04 \x01(\x0b\x32\x1d.widget.EditProfileWidget.CTA\x1a\x34\n\x03\x43TA\x12\r\n\x05label\x18\x01 \x01(\t\x12\x1e\n\x07\x61\x63tions\x18\x02 \x01(\x0b\x32\r.base.ActionsJ\x04\x08\x02\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.profile_edit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_EDITPROFILEWIDGET_DATA'].fields_by_name['delete_label']._loaded_options = None
  _globals['_EDITPROFILEWIDGET_DATA'].fields_by_name['delete_label']._serialized_options = b'\030\001'
  _globals['_EDITPROFILEWIDGET_DATA'].fields_by_name['maturity_text']._loaded_options = None
  _globals['_EDITPROFILEWIDGET_DATA'].fields_by_name['maturity_text']._serialized_options = b'\030\001'
  _globals['_EDITPROFILEWIDGET']._serialized_start=85
  _globals['_EDITPROFILEWIDGET']._serialized_end=749
  _globals['_EDITPROFILEWIDGET_DATA']._serialized_start=198
  _globals['_EDITPROFILEWIDGET_DATA']._serialized_end=549
  _globals['_EDITPROFILEWIDGET_DELETEOPTION']._serialized_start=552
  _globals['_EDITPROFILEWIDGET_DELETEOPTION']._serialized_end=689
  _globals['_EDITPROFILEWIDGET_CTA']._serialized_start=691
  _globals['_EDITPROFILEWIDGET_CTA']._serialized_end=743
# @@protoc_insertion_point(module_scope)
