# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/selectable_horizontal_content_card.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/selectable_horizontal_content_card.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import widget_commons_pb2 as base_dot_widget__commons__pb2
from feature.image import image_pb2 as feature_dot_image_dot_image__pb2
from base import actions_pb2 as base_dot_actions__pb2
from feature.image import lottie_pb2 as feature_dot_image_dot_lottie__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/widget/selectable_horizontal_content_card.proto\x12\x06widget\x1a\x19\x62\x61se/widget_commons.proto\x1a\x19\x66\x65\x61ture/image/image.proto\x1a\x12\x62\x61se/actions.proto\x1a\x1a\x66\x65\x61ture/image/lottie.proto\"\xec\x03\n%SelectableHorizontalContentCardWidget\x12+\n\x0ewidget_commons\x18\x01 \x01(\x0b\x32\x13.base.WidgetCommons\x12@\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32\x32.widget.SelectableHorizontalContentCardWidget.Data\x1a\xcd\x02\n\x04\x44\x61ta\x12\n\n\x02id\x18\x01 \x01(\t\x12-\n\x0fthumbnail_image\x18\x02 \x01(\x0b\x32\x14.feature.image.Image\x12)\n\x0btitle_image\x18\x03 \x01(\x0b\x32\x14.feature.image.Image\x12\x15\n\rsubtitle_text\x18\x04 \x01(\t\x12\x1e\n\x07\x61\x63tions\x18\x05 \x01(\x0b\x32\r.base.Actions\x12\x15\n\rshow_selector\x18\x06 \x01(\x08\x12\x15\n\rshow_gradient\x18\x07 \x01(\x08\x12%\n\x06lottie\x18\x08 \x01(\x0b\x32\x15.feature.image.Lottie\x12#\n\x05image\x18\t \x01(\x0b\x32\x14.feature.image.Image\x12\x1a\n\x12is_stacked_card_ui\x18\n \x01(\x08\x12\x12\n\ncard_label\x18\x0b \x03(\tJ\x04\x08\x02\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.selectable_horizontal_content_card_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_SELECTABLEHORIZONTALCONTENTCARDWIDGET']._serialized_start=162
  _globals['_SELECTABLEHORIZONTALCONTENTCARDWIDGET']._serialized_end=654
  _globals['_SELECTABLEHORIZONTALCONTENTCARDWIDGET_DATA']._serialized_start=315
  _globals['_SELECTABLEHORIZONTALCONTENTCARDWIDGET_DATA']._serialized_end=648
# @@protoc_insertion_point(module_scope)
