# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/single_family_usp.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/single_family_usp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import template_pb2 as base_dot_template__pb2
from base import widget_commons_pb2 as base_dot_widget__commons__pb2
from feature.image import image_pb2 as feature_dot_image_dot_image__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ewidget/single_family_usp.proto\x12\x06widget\x1a\x13\x62\x61se/template.proto\x1a\x19\x62\x61se/widget_commons.proto\x1a\x19\x66\x65\x61ture/image/image.proto\"\x8a\x03\n\x15SingleFamilyUSPWidget\x12$\n\x08template\x18\x01 \x01(\x0b\x32\x0e.base.TemplateB\x02\x18\x01\x12+\n\x0ewidget_commons\x18\x02 \x01(\x0b\x32\x13.base.WidgetCommons\x12\x30\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32\".widget.SingleFamilyUSPWidget.Data\x1ay\n\x04\x44\x61ta\x12\x38\n\x08usp_list\x18\x01 \x03(\x0b\x32&.widget.SingleFamilyUSPWidget.IconText\x12\x37\n\x08usp_grid\x18\x02 \x03(\x0b\x32%.widget.SingleFamilyUSPWidget.USPGrid\x1a=\n\x07USPGrid\x12#\n\x05image\x18\x01 \x01(\x0b\x32\x14.feature.image.Image\x12\r\n\x05label\x18\x02 \x01(\t\x1a,\n\x08IconText\x12\x11\n\ticon_name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tJ\x04\x08\x03\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.single_family_usp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_SINGLEFAMILYUSPWIDGET'].fields_by_name['template']._loaded_options = None
  _globals['_SINGLEFAMILYUSPWIDGET'].fields_by_name['template']._serialized_options = b'\030\001'
  _globals['_SINGLEFAMILYUSPWIDGET']._serialized_start=118
  _globals['_SINGLEFAMILYUSPWIDGET']._serialized_end=512
  _globals['_SINGLEFAMILYUSPWIDGET_DATA']._serialized_start=276
  _globals['_SINGLEFAMILYUSPWIDGET_DATA']._serialized_end=397
  _globals['_SINGLEFAMILYUSPWIDGET_USPGRID']._serialized_start=399
  _globals['_SINGLEFAMILYUSPWIDGET_USPGRID']._serialized_end=460
  _globals['_SINGLEFAMILYUSPWIDGET_ICONTEXT']._serialized_start=462
  _globals['_SINGLEFAMILYUSPWIDGET_ICONTEXT']._serialized_end=506
# @@protoc_insertion_point(module_scope)
