# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/sports_cricket_player.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/sports_cricket_player.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import widget_commons_pb2 as base_dot_widget__commons__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"widget/sports_cricket_player.proto\x12\x06widget\x1a\x19\x62\x61se/widget_commons.proto\"\xd4\x01\n\rCricketPlayer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nshort_desc\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65tail_desc\x18\x03 \x01(\t\x12\x33\n\nplay_state\x18\x04 \x01(\x0e\x32\x1f.widget.CricketPlayer.PlayState\x12\x17\n\x0fplay_state_desc\x18\x05 \x01(\t\">\n\tPlayState\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nYET_TO_BAT\x10\x01\x12\x0b\n\x07NOT_OUT\x10\x02\x12\x07\n\x03OUT\x10\x03\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.sports_cricket_player_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_CRICKETPLAYER']._serialized_start=74
  _globals['_CRICKETPLAYER']._serialized_end=286
  _globals['_CRICKETPLAYER_PLAYSTATE']._serialized_start=224
  _globals['_CRICKETPLAYER_PLAYSTATE']._serialized_end=286
# @@protoc_insertion_point(module_scope)
