# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/sports_masthead.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/sports_masthead.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import template_pb2 as base_dot_template__pb2
from base import widget_commons_pb2 as base_dot_widget__commons__pb2
from base import actions_pb2 as base_dot_actions__pb2
from feature.image import image_pb2 as feature_dot_image_dot_image__pb2
from feature.live import live_info_pb2 as feature_dot_live_dot_live__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cwidget/sports_masthead.proto\x12\x06widget\x1a\x13\x62\x61se/template.proto\x1a\x19\x62\x61se/widget_commons.proto\x1a\x12\x62\x61se/actions.proto\x1a\x19\x66\x65\x61ture/image/image.proto\x1a\x1c\x66\x65\x61ture/live/live_info.proto\"\xb4\x06\n\x14SportsMastheadWidget\x12+\n\x0ewidget_commons\x18\x01 \x01(\x0b\x32\x13.base.WidgetCommons\x12/\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32!.widget.SportsMastheadWidget.Data\x1a\x97\x01\n\x04\x44\x61ta\x12&\n\x08hero_img\x18\x01 \x01(\x0b\x32\x14.feature.image.Image\x12\'\n\tthumbnail\x18\x02 \x01(\x0b\x32\x14.feature.image.Image\x12>\n\x0c\x63ontent_info\x18\x03 \x01(\x0b\x32(.widget.SportsMastheadWidget.ContentInfo\x1a\x84\x03\n\x0b\x43ontentInfo\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x41\n\x0bprimary_cta\x18\x03 \x01(\x0b\x32,.widget.SportsMastheadWidget.IconLabelButton\x12\x1e\n\x07\x61\x63tions\x18\x04 \x01(\x0b\x32\r.base.Actions\x12\x38\n\x0e\x63ore_meta_tags\x18\x05 \x03(\x0b\x32 .widget.SportsMastheadWidget.Tag\x12O\n\x0fhero_image_type\x18\x06 \x01(\x0e\x32\x36.widget.SportsMastheadWidget.ContentInfo.HeroImageType\x12)\n\tlive_info\x18\x07 \x01(\x0b\x32\x16.feature.live.LiveInfo\"8\n\rHeroImageType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08STANDARD\x10\x01\x12\x0c\n\x08\x46\x41LLBACK\x10\x02\x1aS\n\x0fIconLabelButton\x12\x11\n\ticon_name\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x1e\n\x07\x61\x63tions\x18\x03 \x01(\x0b\x32\r.base.Actions\x1a\x42\n\x03Tag\x12\r\n\x05value\x18\x01 \x01(\t\x12\x1e\n\x07\x61\x63tions\x18\x02 \x01(\x0b\x32\r.base.Actions\x12\x0c\n\x04type\x18\x03 \x01(\tJ\x04\x08\x02\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.sports_masthead_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_SPORTSMASTHEADWIDGET']._serialized_start=166
  _globals['_SPORTSMASTHEADWIDGET']._serialized_end=986
  _globals['_SPORTSMASTHEADWIDGET_DATA']._serialized_start=285
  _globals['_SPORTSMASTHEADWIDGET_DATA']._serialized_end=436
  _globals['_SPORTSMASTHEADWIDGET_CONTENTINFO']._serialized_start=439
  _globals['_SPORTSMASTHEADWIDGET_CONTENTINFO']._serialized_end=827
  _globals['_SPORTSMASTHEADWIDGET_CONTENTINFO_HEROIMAGETYPE']._serialized_start=771
  _globals['_SPORTSMASTHEADWIDGET_CONTENTINFO_HEROIMAGETYPE']._serialized_end=827
  _globals['_SPORTSMASTHEADWIDGET_ICONLABELBUTTON']._serialized_start=829
  _globals['_SPORTSMASTHEADWIDGET_ICONLABELBUTTON']._serialized_end=912
  _globals['_SPORTSMASTHEADWIDGET_TAG']._serialized_start=914
  _globals['_SPORTSMASTHEADWIDGET_TAG']._serialized_end=980
# @@protoc_insertion_point(module_scope)
