# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/square_studio_card.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/square_studio_card.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import template_pb2 as base_dot_template__pb2
from base import widget_commons_pb2 as base_dot_widget__commons__pb2
from feature.image import image_pb2 as feature_dot_image_dot_image__pb2
from base import actions_pb2 as base_dot_actions__pb2
from feature.animation import video_animation_pb2 as feature_dot_animation_dot_video__animation__pb2
from widget import spotlight_info_pb2 as widget_dot_spotlight__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fwidget/square_studio_card.proto\x12\x06widget\x1a\x13\x62\x61se/template.proto\x1a\x19\x62\x61se/widget_commons.proto\x1a\x19\x66\x65\x61ture/image/image.proto\x1a\x12\x62\x61se/actions.proto\x1a\'feature/animation/video_animation.proto\x1a\x1bwidget/spotlight_info.proto\"\xb4\x04\n\x16SquareStudioCardWidget\x12$\n\x08template\x18\x01 \x01(\x0b\x32\x0e.base.TemplateB\x02\x18\x01\x12+\n\x0ewidget_commons\x18\x02 \x01(\x0b\x32\x13.base.WidgetCommons\x12\x31\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32#.widget.SquareStudioCardWidget.Data\x1a\x93\x02\n\x04\x44\x61ta\x12#\n\x05image\x18\x01 \x01(\x0b\x32\x14.feature.image.Image\x12\x1e\n\x07\x61\x63tions\x18\x02 \x01(\x0b\x32\r.base.Actions\x12:\n\x0fvideo_animation\x18\x03 \x01(\x0b\x32!.feature.animation.VideoAnimation\x12U\n\x17\x65xpanded_content_poster\x18\x04 \x01(\x0b\x32\x34.widget.SquareStudioCardWidget.ExpandedContentPoster\x12\x33\n\x0espotlight_info\x18\x05 \x01(\x0b\x32\x1b.widget.SpotlightInfoWidget\x1ax\n\x15\x45xpandedContentPoster\x12#\n\x05image\x18\x01 \x01(\x0b\x32\x14.feature.image.Image\x12:\n\x0fvideo_animation\x18\x02 \x01(\x0b\x32!.feature.animation.VideoAnimationJ\x04\x08\x03\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.square_studio_card_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_SQUARESTUDIOCARDWIDGET'].fields_by_name['template']._loaded_options = None
  _globals['_SQUARESTUDIOCARDWIDGET'].fields_by_name['template']._serialized_options = b'\030\001'
  _globals['_SQUARESTUDIOCARDWIDGET']._serialized_start=209
  _globals['_SQUARESTUDIOCARDWIDGET']._serialized_end=773
  _globals['_SQUARESTUDIOCARDWIDGET_DATA']._serialized_start=370
  _globals['_SQUARESTUDIOCARDWIDGET_DATA']._serialized_end=645
  _globals['_SQUARESTUDIOCARDWIDGET_EXPANDEDCONTENTPOSTER']._serialized_start=647
  _globals['_SQUARESTUDIOCARDWIDGET_EXPANDEDCONTENTPOSTER']._serialized_end=767
# @@protoc_insertion_point(module_scope)
