# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/sub_navigation_text.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/sub_navigation_text.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import template_pb2 as base_dot_template__pb2
from base import widget_commons_pb2 as base_dot_widget__commons__pb2
from base import actions_pb2 as base_dot_actions__pb2
from feature.image import image_pb2 as feature_dot_image_dot_image__pb2
from feature.animation import video_animation_pb2 as feature_dot_animation_dot_video__animation__pb2
from feature.image import lottie_pb2 as feature_dot_image_dot_lottie__pb2
from widget import info_pill_pb2 as widget_dot_info__pill__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n widget/sub_navigation_text.proto\x12\x06widget\x1a\x13\x62\x61se/template.proto\x1a\x19\x62\x61se/widget_commons.proto\x1a\x12\x62\x61se/actions.proto\x1a\x19\x66\x65\x61ture/image/image.proto\x1a\'feature/animation/video_animation.proto\x1a\x1a\x66\x65\x61ture/image/lottie.proto\x1a\x16widget/info_pill.proto\"\x89\x07\n\x13SubNavigationWidget\x12+\n\x0ewidget_commons\x18\x02 \x01(\x0b\x32\x13.base.WidgetCommons\x12.\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32 .widget.SubNavigationWidget.Data\x1a\xbc\x02\n\x04\x44\x61ta\x12\x33\n\x05items\x18\x0b \x03(\x0b\x32 .widget.SubNavigationWidget.ItemB\x02\x18\x01\x12/\n\x18\x63lose_navigation_actions\x18\x0c \x01(\x0b\x32\r.base.Actions\x12\x1d\n\x15\x63lose_navigation_icon\x18\r \x01(\t\x12?\n\x0esub_menu_items\x18\x0e \x03(\x0b\x32\'.widget.SubNavigationWidget.SubMenuItem\x12?\n\x10\x61nimatation_meta\x18\x0f \x03(\x0b\x32!.feature.animation.VideoAnimationB\x02\x18\x01\x12-\n\x0e\x61nimation_meta\x18\x10 \x03(\x0b\x32\x15.feature.image.Lottie\x1a}\n\x0bSubMenuItem\x12\x30\n\x04item\x18\x01 \x01(\x0b\x32 .widget.SubNavigationWidget.ItemH\x00\x12+\n\tinfo_pill\x18\x02 \x01(\x0b\x32\x16.widget.InfoPillWidgetH\x00\x42\x0f\n\rsub_menu_item\x1a\xb4\x01\n\x04Item\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tis_active\x18\x03 \x01(\x08\x12\x1e\n\x07\x61\x63tions\x18\x04 \x01(\x0b\x32\r.base.Actions\x12\n\n\x02id\x18\x05 \x01(\t\x12\x0c\n\x04icon\x18\x06 \x01(\t\x12\x16\n\x0eis_collapsible\x18\x07 \x01(\x08\x12\x38\n\tanimation\x18\x08 \x01(\x0b\x32%.widget.SubNavigationWidget.Animation\x1a\x61\n\tAnimation\x12G\n\x10\x61nimating_images\x18\x01 \x01(\x0b\x32+.widget.SubNavigationWidget.AnimatingImagesH\x00\x42\x0b\n\tanimation\x1a\x37\n\x0f\x41nimatingImages\x12$\n\x06images\x18\x01 \x03(\x0b\x32\x14.feature.image.ImageJ\x04\x08\x03\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.sub_navigation_text_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_SUBNAVIGATIONWIDGET_DATA'].fields_by_name['items']._loaded_options = None
  _globals['_SUBNAVIGATIONWIDGET_DATA'].fields_by_name['items']._serialized_options = b'\030\001'
  _globals['_SUBNAVIGATIONWIDGET_DATA'].fields_by_name['animatation_meta']._loaded_options = None
  _globals['_SUBNAVIGATIONWIDGET_DATA'].fields_by_name['animatation_meta']._serialized_options = b'\030\001'
  _globals['_SUBNAVIGATIONWIDGET']._serialized_start=233
  _globals['_SUBNAVIGATIONWIDGET']._serialized_end=1138
  _globals['_SUBNAVIGATIONWIDGET_DATA']._serialized_start=350
  _globals['_SUBNAVIGATIONWIDGET_DATA']._serialized_end=666
  _globals['_SUBNAVIGATIONWIDGET_SUBMENUITEM']._serialized_start=668
  _globals['_SUBNAVIGATIONWIDGET_SUBMENUITEM']._serialized_end=793
  _globals['_SUBNAVIGATIONWIDGET_ITEM']._serialized_start=796
  _globals['_SUBNAVIGATIONWIDGET_ITEM']._serialized_end=976
  _globals['_SUBNAVIGATIONWIDGET_ANIMATION']._serialized_start=978
  _globals['_SUBNAVIGATIONWIDGET_ANIMATION']._serialized_end=1075
  _globals['_SUBNAVIGATIONWIDGET_ANIMATINGIMAGES']._serialized_start=1077
  _globals['_SUBNAVIGATIONWIDGET_ANIMATINGIMAGES']._serialized_end=1132
# @@protoc_insertion_point(module_scope)
