# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/unified_attention_tray.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/unified_attention_tray.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import widget_commons_pb2 as base_dot_widget__commons__pb2
from feature.refresh import refresh_info_pb2 as feature_dot_refresh_dot_refresh__info__pb2
from widget import uat_vertical_content_poster_pb2 as widget_dot_uat__vertical__content__poster__pb2
from widget import header_pb2 as widget_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#widget/unified_attention_tray.proto\x12\x06widget\x1a\x19\x62\x61se/widget_commons.proto\x1a\"feature/refresh/refresh_info.proto\x1a(widget/uat_vertical_content_poster.proto\x1a\x13widget/header.proto\"\x9f\x03\n\x1aUnifiedAttentionTrayWidget\x12+\n\x0ewidget_commons\x18\x01 \x01(\x0b\x32\x13.base.WidgetCommons\x12\x35\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32\'.widget.UnifiedAttentionTrayWidget.Data\x1a\xb5\x01\n\x04\x44\x61ta\x12\x1a\n\x12item_template_name\x18\x01 \x01(\t\x12)\n\x0btray_header\x18\x02 \x01(\x0b\x32\x14.widget.HeaderWidget\x12\x15\n\rnext_tray_url\x18\x03 \x01(\t\x12\x36\n\x05items\x18\x04 \x03(\x0b\x32\'.widget.UnifiedAttentionTrayWidget.Item\x12\x17\n\x0fshould_fallback\x18\x05 \x01(\x08\x1a_\n\x04Item\x12M\n\x1buat_vertical_content_poster\x18\x01 \x01(\x0b\x32&.widget.UatVerticalContentPosterWidgetH\x00\x42\x08\n\x06widgetJ\x04\x08\x02\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.unified_attention_tray_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_UNIFIEDATTENTIONTRAYWIDGET']._serialized_start=174
  _globals['_UNIFIEDATTENTIONTRAYWIDGET']._serialized_end=589
  _globals['_UNIFIEDATTENTIONTRAYWIDGET_DATA']._serialized_start=305
  _globals['_UNIFIEDATTENTIONTRAYWIDGET_DATA']._serialized_end=486
  _globals['_UNIFIEDATTENTIONTRAYWIDGET_ITEM']._serialized_start=488
  _globals['_UNIFIEDATTENTIONTRAYWIDGET_ITEM']._serialized_end=583
# @@protoc_insertion_point(module_scope)
