# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/usp_details.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/usp_details.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import widget_commons_pb2 as base_dot_widget__commons__pb2
from widget import image_banner_pb2 as widget_dot_image__banner__pb2
from feature.branding import brand_pb2 as feature_dot_branding_dot_brand__pb2
from widget import grid_pb2 as widget_dot_grid__pb2
from base import actions_pb2 as base_dot_actions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18widget/usp_details.proto\x12\x06widget\x1a\x19\x62\x61se/widget_commons.proto\x1a\x19widget/image_banner.proto\x1a\x1c\x66\x65\x61ture/branding/brand.proto\x1a\x11widget/grid.proto\x1a\x12\x62\x61se/actions.proto\"\xcb\x02\n\x10USPDetailsWidget\x12+\n\x0ewidget_commons\x18\x02 \x01(\x0b\x32\x13.base.WidgetCommons\x12+\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32\x1d.widget.USPDetailsWidget.Data\x1ah\n\x04\x44\x61ta\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08subtitle\x18\x02 \x01(\t\x12\x12\n\nbackground\x18\x03 \x01(\t\x12+\n\x04item\x18\x04 \x01(\x0b\x32\x1d.widget.USPDetailsWidget.Item\x1ag\n\x04Item\x12\x31\n\x0cimage_banner\x18\x01 \x01(\x0b\x32\x19.widget.ImageBannerWidgetH\x00\x12\"\n\x04grid\x18\x02 \x01(\x0b\x32\x12.widget.GridWidgetH\x00\x42\x08\n\x06widgetJ\x04\x08\x01\x10\x02J\x04\x08\x03\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.usp_details_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_USPDETAILSWIDGET']._serialized_start=160
  _globals['_USPDETAILSWIDGET']._serialized_end=491
  _globals['_USPDETAILSWIDGET_DATA']._serialized_start=270
  _globals['_USPDETAILSWIDGET_DATA']._serialized_end=374
  _globals['_USPDETAILSWIDGET_ITEM']._serialized_start=376
  _globals['_USPDETAILSWIDGET_ITEM']._serialized_end=479
# @@protoc_insertion_point(module_scope)
