# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/usp_item.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/usp_item.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import widget_commons_pb2 as base_dot_widget__commons__pb2
from feature.image import image_pb2 as feature_dot_image_dot_image__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15widget/usp_item.proto\x12\x06widget\x1a\x19\x62\x61se/widget_commons.proto\x1a\x19\x66\x65\x61ture/image/image.proto\"\xfc\x04\n\rUspItemWidget\x12+\n\x0ewidget_commons\x18\x01 \x01(\x0b\x32\x13.base.WidgetCommons\x12(\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32\x1a.widget.UspItemWidget.Data\x1a\x88\x01\n\x04\x44\x61ta\x12\'\n\tusp_image\x18\x01 \x01(\x0b\x32\x14.feature.image.Image\x12-\n\x05label\x18\x02 \x01(\x0b\x32\x1e.widget.UspItemWidget.TextInfo\x12(\n\x04item\x18\x03 \x01(\x0b\x32\x1a.widget.UspItemWidget.Item\x1aV\n\x08TextInfo\x12\x0c\n\x04text\x18\x01 \x01(\t\x12<\n\x0etypographyType\x18\x02 \x01(\x0e\x32$.widget.UspItemWidget.TypographyType\x1a~\n\x04Item\x12\x35\n\x0b\x64\x65scription\x18\x01 \x01(\x0b\x32\x1e.widget.UspItemWidget.TextInfoH\x00\x12\x37\n\tdesc_list\x18\x02 \x01(\x0b\x32\".widget.UspItemWidget.DescTextListH\x00\x42\x06\n\x04Item\x1a&\n\x0c\x44\x65scTextList\x12\x16\n\x0e\x64\x65sc_text_list\x18\x01 \x03(\t\"\x82\x01\n\x0eTypographyType\x12\x06\n\x02H5\x10\x00\x12\x06\n\x02H1\x10\x01\x12\n\n\x06TITLE1\x10\x02\x12\n\n\x06TITLE2\x10\x03\x12\x10\n\x0c\x42ODY1_MEDIUM\x10\x04\x12\x11\n\rBODY2_REGULAR\x10\x05\x12\x11\n\rBODY3_REGULAR\x10\x06\x12\x10\n\x0c\x42ODY2_MEDIUM\x10\x07J\x04\x08\x02\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.usp_item_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_USPITEMWIDGET']._serialized_start=88
  _globals['_USPITEMWIDGET']._serialized_end=724
  _globals['_USPITEMWIDGET_DATA']._serialized_start=193
  _globals['_USPITEMWIDGET_DATA']._serialized_end=329
  _globals['_USPITEMWIDGET_TEXTINFO']._serialized_start=331
  _globals['_USPITEMWIDGET_TEXTINFO']._serialized_end=417
  _globals['_USPITEMWIDGET_ITEM']._serialized_start=419
  _globals['_USPITEMWIDGET_ITEM']._serialized_end=545
  _globals['_USPITEMWIDGET_DESCTEXTLIST']._serialized_start=547
  _globals['_USPITEMWIDGET_DESCTEXTLIST']._serialized_end=585
  _globals['_USPITEMWIDGET_TYPOGRAPHYTYPE']._serialized_start=588
  _globals['_USPITEMWIDGET_TYPOGRAPHYTYPE']._serialized_end=718
# @@protoc_insertion_point(module_scope)
