# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/vertical_large_content_poster.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/vertical_large_content_poster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import template_pb2 as base_dot_template__pb2
from base import widget_commons_pb2 as base_dot_widget__commons__pb2
from base import actions_pb2 as base_dot_actions__pb2
from feature.image import image_pb2 as feature_dot_image_dot_image__pb2
from feature.accessibility import accessibility_pb2 as feature_dot_accessibility_dot_accessibility__pb2
from feature.autoplay import autoplay_info_pb2 as feature_dot_autoplay_dot_autoplay__info__pb2
from feature.content_language_preference import content_language_preference_pb2 as feature_dot_content__language__preference_dot_content__language__preference__pb2
from feature.language import language_pb2 as feature_dot_language_dot_language__pb2
from feature.remind_me import remind_me_info_pb2 as feature_dot_remind__me_dot_remind__me__info__pb2
from feature.watchlist import watchlist_info_pb2 as feature_dot_watchlist_dot_watchlist__info__pb2
from widget import expanded_content_poster_pb2 as widget_dot_expanded__content__poster__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*widget/vertical_large_content_poster.proto\x12\x06widget\x1a\x13\x62\x61se/template.proto\x1a\x19\x62\x61se/widget_commons.proto\x1a\x12\x62\x61se/actions.proto\x1a\x19\x66\x65\x61ture/image/image.proto\x1a)feature/accessibility/accessibility.proto\x1a$feature/autoplay/autoplay_info.proto\x1a\x45\x66\x65\x61ture/content_language_preference/content_language_preference.proto\x1a\x1f\x66\x65\x61ture/language/language.proto\x1a&feature/remind_me/remind_me_info.proto\x1a&feature/watchlist/watchlist_info.proto\x1a$widget/expanded_content_poster.proto\"\x92\x04\n VerticalLargeContentPosterWidget\x12$\n\x08template\x18\x01 \x01(\x0b\x32\x0e.base.TemplateB\x02\x18\x01\x12+\n\x0ewidget_commons\x18\x02 \x01(\x0b\x32\x13.base.WidgetCommons\x12;\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32-.widget.VerticalLargeContentPosterWidget.Data\x1a\xa0\x02\n\x04\x44\x61ta\x12#\n\x05image\x18\x01 \x01(\x0b\x32\x14.feature.image.Image\x12\x1e\n\x07\x61\x63tions\x18\x02 \x01(\x0b\x32\r.base.Actions\x12\x44\n\x17\x65xpanded_content_poster\x18\x03 \x01(\x0b\x32#.widget.ExpandedContentPosterWidget\x12\x46\n\nlive_badge\x18\x04 \x01(\x0b\x32\x32.widget.VerticalLargeContentPosterWidget.LiveBadge\x12\x31\n\x03\x61lt\x18\x05 \x01(\x0b\x32$.feature.accessibility.Accessibility\x12\x12\n\ncontent_id\x18\x06 \x01(\t\x1a\x35\n\tLiveBadge\x12(\n\ntext_image\x18\x01 \x01(\x0b\x32\x14.feature.image.ImageJ\x04\x08\x03\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.vertical_large_content_poster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_VERTICALLARGECONTENTPOSTERWIDGET'].fields_by_name['template']._loaded_options = None
  _globals['_VERTICALLARGECONTENTPOSTERWIDGET'].fields_by_name['template']._serialized_options = b'\030\001'
  _globals['_VERTICALLARGECONTENTPOSTERWIDGET']._serialized_start=453
  _globals['_VERTICALLARGECONTENTPOSTERWIDGET']._serialized_end=983
  _globals['_VERTICALLARGECONTENTPOSTERWIDGET_DATA']._serialized_start=634
  _globals['_VERTICALLARGECONTENTPOSTERWIDGET_DATA']._serialized_end=922
  _globals['_VERTICALLARGECONTENTPOSTERWIDGET_LIVEBADGE']._serialized_start=924
  _globals['_VERTICALLARGECONTENTPOSTERWIDGET_LIVEBADGE']._serialized_end=977
# @@protoc_insertion_point(module_scope)
