# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/vertical_content_card_collection.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/vertical_content_card_collection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from widget import header_pb2 as widget_dot_header__pb2
from widget import hero_gec_pb2 as widget_dot_hero__gec__pb2
from base import widget_commons_pb2 as base_dot_widget__commons__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-widget/vertical_content_card_collection.proto\x12\x06widget\x1a\x13widget/header.proto\x1a\x15widget/hero_gec.proto\x1a\x19\x62\x61se/widget_commons.proto\"\xc4\x02\n#VerticalContentCardCollectionWidget\x12+\n\x0ewidget_commons\x18\x01 \x01(\x0b\x32\x13.base.WidgetCommons\x12>\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32\x30.widget.VerticalContentCardCollectionWidget.Data\x1am\n\x04\x44\x61ta\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.widget.HeaderWidget\x12?\n\x05items\x18\x02 \x03(\x0b\x32\x30.widget.VerticalContentCardCollectionWidget.Item\x1a;\n\x04Item\x12)\n\x08hero_gec\x18\x01 \x01(\x0b\x32\x15.widget.HeroGECWidgetH\x00\x42\x08\n\x06widgetJ\x04\x08\x02\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.vertical_content_card_collection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_VERTICALCONTENTCARDCOLLECTIONWIDGET']._serialized_start=129
  _globals['_VERTICALCONTENTCARDCOLLECTIONWIDGET']._serialized_end=453
  _globals['_VERTICALCONTENTCARDCOLLECTIONWIDGET_DATA']._serialized_start=277
  _globals['_VERTICALCONTENTCARDCOLLECTIONWIDGET_DATA']._serialized_end=386
  _globals['_VERTICALCONTENTCARDCOLLECTIONWIDGET_ITEM']._serialized_start=388
  _globals['_VERTICALCONTENTCARDCOLLECTIONWIDGET_ITEM']._serialized_end=447
# @@protoc_insertion_point(module_scope)
