# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widget/watchlist_tray.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'widget/watchlist_tray.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import template_pb2 as base_dot_template__pb2
from base import widget_commons_pb2 as base_dot_widget__commons__pb2
from base import actions_pb2 as base_dot_actions__pb2
from widget import header_pb2 as widget_dot_header__pb2
from widget import vertical_content_poster_pb2 as widget_dot_vertical__content__poster__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bwidget/watchlist_tray.proto\x12\x06widget\x1a\x13\x62\x61se/template.proto\x1a\x19\x62\x61se/widget_commons.proto\x1a\x12\x62\x61se/actions.proto\x1a\x13widget/header.proto\x1a$widget/vertical_content_poster.proto\"\xea\x05\n\x0fWatchlistWidget\x12$\n\x08template\x18\x01 \x01(\x0b\x32\x0e.base.TemplateB\x02\x18\x01\x12+\n\x0ewidget_commons\x18\x02 \x01(\x0b\x32\x13.base.WidgetCommons\x12*\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32\x1c.widget.WatchlistWidget.Data\x1a\x81\x02\n\x04\x44\x61ta\x12\x32\n\x06header\x18\x01 \x01(\x0b\x32\x1e.widget.WatchlistWidget.HeaderB\x02\x18\x01\x12+\n\x05items\x18\x03 \x03(\x0b\x32\x1c.widget.WatchlistWidget.Item\x12\x1a\n\x12next_watchlist_url\x18\x04 \x01(\t\x12\x39\n\x0crefresh_info\x18\x05 \x01(\x0b\x32#.widget.WatchlistWidget.RefreshInfo\x12)\n\x0btray_header\x18\x06 \x01(\x0b\x32\x14.widget.HeaderWidgetJ\x04\x08\x02\x10\x03R\x10more_widgets_url\x1a\x36\n\x0bRefreshInfo\x12\x12\n\nmax_age_ms\x18\x01 \x01(\x03\x12\x13\n\x0brefresh_url\x18\x02 \x01(\t\x1aj\n\x06Header\x12\r\n\x05title\x18\x01 \x01(\t\x12\x1e\n\x07\x61\x63tions\x18\x02 \x01(\x0b\x32\r.base.Actions\x12\x31\n\x03\x63ta\x18\x03 \x01(\x0b\x32$.widget.WatchlistWidget.IconLabelCTA\x1aX\n\x04Item\x12\x46\n\x17vertical_content_poster\x18\x01 \x01(\x0b\x32#.widget.VerticalContentPosterWidgetH\x00\x42\x08\n\x06widget\x1aP\n\x0cIconLabelCTA\x12\r\n\x05label\x18\x01 \x01(\t\x12\x11\n\ticon_name\x18\x02 \x01(\t\x12\x1e\n\x07\x61\x63tions\x18\x03 \x01(\x0b\x32\r.base.ActionsJ\x04\x08\x03\x10\x0b\x42O\n\x1b\x63om.hotstar.ui.model.widgetP\x01Z.github.com/hotstar/hs-core-ui-models-go/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widget.watchlist_tray_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.hotstar.ui.model.widgetP\001Z.github.com/hotstar/hs-core-ui-models-go/widget'
  _globals['_WATCHLISTWIDGET_DATA'].fields_by_name['header']._loaded_options = None
  _globals['_WATCHLISTWIDGET_DATA'].fields_by_name['header']._serialized_options = b'\030\001'
  _globals['_WATCHLISTWIDGET'].fields_by_name['template']._loaded_options = None
  _globals['_WATCHLISTWIDGET'].fields_by_name['template']._serialized_options = b'\030\001'
  _globals['_WATCHLISTWIDGET']._serialized_start=167
  _globals['_WATCHLISTWIDGET']._serialized_end=913
  _globals['_WATCHLISTWIDGET_DATA']._serialized_start=314
  _globals['_WATCHLISTWIDGET_DATA']._serialized_end=571
  _globals['_WATCHLISTWIDGET_REFRESHINFO']._serialized_start=573
  _globals['_WATCHLISTWIDGET_REFRESHINFO']._serialized_end=627
  _globals['_WATCHLISTWIDGET_HEADER']._serialized_start=629
  _globals['_WATCHLISTWIDGET_HEADER']._serialized_end=735
  _globals['_WATCHLISTWIDGET_ITEM']._serialized_start=737
  _globals['_WATCHLISTWIDGET_ITEM']._serialized_end=825
  _globals['_WATCHLISTWIDGET_ICONLABELCTA']._serialized_start=827
  _globals['_WATCHLISTWIDGET_ICONLABELCTA']._serialized_end=907
# @@protoc_insertion_point(module_scope)
