# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/base/batch_metadata.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'api/base/batch_metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61pi/base/batch_metadata.proto\x12\x08\x61pi.base\"\xd5\x01\n\rBatchMetadata\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\t\x12\x18\n\x10\x62\x61tch_size_bytes\x18\x02 \x01(\r\x12\x19\n\x11\x63ommon_size_bytes\x18\x03 \x01(\r\x12\x18\n\x10\x65vent_size_bytes\x18\x04 \x01(\r\x12\x18\n\x10\x62\x61tch_num_events\x18\x05 \x01(\r\x12\"\n\x1arequest_payload_size_bytes\x18\x06 \x01(\r\x12%\n\x1dis_request_payload_compressed\x18\x07 \x01(\x08\x42\x63\n com.hotstar.event.model.api.baseP\x01Z=github.com/hotstar/data-event-schemas-go/hsanalytics/api/baseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.base.batch_metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.hotstar.event.model.api.baseP\001Z=github.com/hotstar/data-event-schemas-go/hsanalytics/api/base'
  _globals['_BATCHMETADATA']._serialized_start=44
  _globals['_BATCHMETADATA']._serialized_end=257
# @@protoc_insertion_point(module_scope)
