# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/download/properties/completed_download_properties.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/download/properties/completed_download_properties.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from client.download.model import download_request_info_pb2 as client_dot_download_dot_model_dot_download__request__info__pb2
from client.download.model import download_session_info_pb2 as client_dot_download_dot_model_dot_download__session__info__pb2
from client.download.model import download_size_info_pb2 as client_dot_download_dot_model_dot_download__size__info__pb2
from client.download.model import download_stat_info_pb2 as client_dot_download_dot_model_dot_download__stat__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>client/download/properties/completed_download_properties.proto\x12\x1a\x63lient.download.properties\x1a\x31\x63lient/download/model/download_request_info.proto\x1a\x31\x63lient/download/model/download_session_info.proto\x1a.client/download/model/download_size_info.proto\x1a.client/download/model/download_stat_info.proto\"\xdc\x02\n\x1b\x43ompletedDownloadProperties\x12I\n\x15\x64ownload_session_info\x18\x01 \x01(\x0b\x32*.client.download.model.DownloadSessionInfo\x12\x43\n\x12\x64ownload_stat_info\x18\x02 \x01(\x0b\x32\'.client.download.model.DownloadStatInfo\x12\x43\n\x12\x64ownload_size_info\x18\x03 \x01(\x0b\x32\'.client.download.model.DownloadSizeInfo\x12I\n\x15\x64ownload_request_info\x18\x04 \x01(\x0b\x32*.client.download.model.DownloadRequestInfo\x12\x1d\n\x15\x61verage_speed_in_mbps\x18\x05 \x01(\x04\x42\x87\x01\n2com.hotstar.event.model.client.download.propertiesP\x01ZOgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/download/propertiesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.download.properties.completed_download_properties_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n2com.hotstar.event.model.client.download.propertiesP\001ZOgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/download/properties'
  _globals['_COMPLETEDDOWNLOADPROPERTIES']._serialized_start=293
  _globals['_COMPLETEDDOWNLOADPROPERTIES']._serialized_end=641
# @@protoc_insertion_point(module_scope)
