# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: component/proto_test_mineva_data.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'component/proto_test_mineva_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from options import opts_pb2 as options_dot_opts__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&component/proto_test_mineva_data.proto\x12\tcomponent\x1a\x12options/opts.proto\"\x96\x02\n\x14ProtoTestMinervaData\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x16\n\x0ets_received_ms\x18\x02 \x01(\x04\x12\x10\n\x08test_str\x18\x03 \x01(\t\x12\x13\n\x0btest_uint64\x18\x04 \x01(\x04\x12\x14\n\x0ctest_fixed32\x18\x05 \x01(\x07\x12\x15\n\rtest_sfixed64\x18\x06 \x01(\x10\x12\x12\n\ntest_float\x18\x07 \x01(\x02\x12\x13\n\x0btest_double\x18\x08 \x01(\x01\x12\x11\n\ttest_bool\x18\t \x01(\x08\x12\x18\n\x0etest_oneof_str\x18\n \x01(\tH\x00\x12\x1a\n\x10test_oneof_int32\x18\x0b \x01(\x05H\x00\x42\x0c\n\ntest_oneof\"\x1e\n\x0bTestMessage\x12\x0f\n\x07msg_str\x18\x01 \x01(\t\"\xdd\x03\n\x15ProtoTestMinervaData2\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x16\n\x0ets_received_ms\x18\x02 \x01(\x04\x12\x13\n\x0btest2_int32\x18\x03 \x01(\x05\x12\'\n\ntest2_enum\x18\x04 \x01(\x0e\x32\x13.component.TestEnum\x12,\n\x0frep_test2_enums\x18\x05 \x03(\x0e\x32\x13.component.TestEnum\x12\x16\n\x0erep_test2_strs\x18\x06 \x03(\t\x12)\n\ttest2_msg\x18\x08 \x01(\x0b\x32\x16.component.TestMessage\x12.\n\x0erep_test2_msgs\x18\x0c \x03(\x0b\x32\x16.component.TestMessage\x12\x41\n\ttest2_map\x18\x0b \x03(\x0b\x32..component.ProtoTestMinervaData2.Test2MapEntry\x12\x19\n\x0ftest2_oneof_str\x18\t \x01(\tH\x00\x12\x1b\n\x11test2_oneof_int32\x18\n \x01(\x05H\x00\x1a/\n\rTest2MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x42\r\n\x0btest2_oneof*K\n\x08TestEnum\x12\x19\n\x15TEST_ENUM_UNSPECIFIED\x10\x00\x12\x11\n\rTEST_ENUM_OK1\x10\x01\x12\x11\n\rTEST_ENUM_OK2\x10\x02\x42\x65\n!com.hotstar.event.model.componentP\x01Z>github.com/hotstar/data-event-schemas-go/hsanalytics/componentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'component.proto_test_mineva_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.hotstar.event.model.componentP\001Z>github.com/hotstar/data-event-schemas-go/hsanalytics/component'
  _globals['_PROTOTESTMINERVADATA2_TEST2MAPENTRY']._loaded_options = None
  _globals['_PROTOTESTMINERVADATA2_TEST2MAPENTRY']._serialized_options = b'8\001'
  _globals['_TESTENUM']._serialized_start=866
  _globals['_TESTENUM']._serialized_end=941
  _globals['_PROTOTESTMINERVADATA']._serialized_start=74
  _globals['_PROTOTESTMINERVADATA']._serialized_end=352
  _globals['_TESTMESSAGE']._serialized_start=354
  _globals['_TESTMESSAGE']._serialized_end=384
  _globals['_PROTOTESTMINERVADATA2']._serialized_start=387
  _globals['_PROTOTESTMINERVADATA2']._serialized_end=864
  _globals['_PROTOTESTMINERVADATA2_TEST2MAPENTRY']._serialized_start=802
  _globals['_PROTOTESTMINERVADATA2_TEST2MAPENTRY']._serialized_end=849
# @@protoc_insertion_point(module_scope)
