# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/ads/sgai/error.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/ads/sgai/error.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63lient/ads/sgai/error.proto\x12\x0f\x63lient.ads.sgai\"<\n\x05\x45rror\x12\x17\n\x0fsgai_error_code\x18\x01 \x01(\x05\x12\x1a\n\x12sgai_error_message\x18\x02 \x01(\tBq\n\'com.hotstar.event.model.client.ads.sgaiP\x01ZDgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/ads/sgaib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.ads.sgai.error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'com.hotstar.event.model.client.ads.sgaiP\001ZDgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/ads/sgai'
  _globals['_ERROR']._serialized_start=48
  _globals['_ERROR']._serialized_end=108
# @@protoc_insertion_point(module_scope)
