# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/ads/sgai/stitch_attributes.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/ads/sgai/stitch_attributes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'client/ads/sgai/stitch_attributes.proto\x12\x0f\x63lient.ads.sgai\"\xaa\x01\n\x10StitchAttributes\x12\x17\n\x0ftotal_ad_breaks\x18\x01 \x01(\r\x12\x16\n\x0esgai_ad_breaks\x18\x02 \x01(\r\x12\x1a\n\x12stitched_ad_breaks\x18\x03 \x01(\r\x12\x19\n\x11period_cache_hits\x18\x04 \x01(\r\x12\x17\n\x0f\x66use_cache_hits\x18\x05 \x01(\r\x12\x15\n\rtotal_latency\x18\x06 \x01(\x04\x42q\n\'com.hotstar.event.model.client.ads.sgaiP\x01ZDgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/ads/sgaib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.ads.sgai.stitch_attributes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'com.hotstar.event.model.client.ads.sgaiP\001ZDgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/ads/sgai'
  _globals['_STITCHATTRIBUTES']._serialized_start=61
  _globals['_STITCHATTRIBUTES']._serialized_end=231
# @@protoc_insertion_point(module_scope)
