# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/refresh_page.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.v2 import refresh_space_pb2 as v2_dot_refresh__space__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15v2/refresh_page.proto\x12\x02v2\x1a\x16v2/refresh_space.proto\"g\n\x12RefreshPageRequest\x12\x10\n\x08page_url\x18\x03 \x01(\t\x12/\n\x0espace_requests\x18\x0b \x03(\x0b\x32\x17.v2.RefreshSpaceRequest:\x02\x18\x01J\x04\x08\x01\x10\x03J\x04\x08\x05\x10\x0b\"x\n\x13\x44\x65\x66\x65rredPageRequest\x12\x10\n\x08page_url\x18\x03 \x01(\t\x12\x11\n\tpage_slug\x18\x04 \x01(\t\x12\x30\n\x0espace_requests\x18\x0b \x03(\x0b\x32\x18.v2.DeferredSpaceRequestJ\x04\x08\x01\x10\x03J\x04\x08\x05\x10\x0b\x42@\n\x16\x63om.hotstar.bff.api.v2P\x01Z$github.com/hotstar/hs-core-api-go/v2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v2.refresh_page_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.hotstar.bff.api.v2P\001Z$github.com/hotstar/hs-core-api-go/v2'
  _REFRESHPAGEREQUEST._options = None
  _REFRESHPAGEREQUEST._serialized_options = b'\030\001'
  _globals['_REFRESHPAGEREQUEST']._serialized_start=53
  _globals['_REFRESHPAGEREQUEST']._serialized_end=156
  _globals['_DEFERREDPAGEREQUEST']._serialized_start=158
  _globals['_DEFERREDPAGEREQUEST']._serialized_end=278
# @@protoc_insertion_point(module_scope)
