# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v2/refresh_widget.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'v2/refresh_widget.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17v2/refresh_widget.proto\x12\x02v2\"Y\n\x14RefreshWidgetRequest\x12\x1d\n\x11widget_wrapper_id\x18\x01 \x01(\tB\x02\x18\x01\x12\x12\n\nwidget_url\x18\x03 \x01(\t:\x02\x18\x01J\x04\x08\x02\x10\x03J\x04\x08\x04\x10\x0b\"R\n\x15\x44\x65\x66\x65rredWidgetRequest\x12\x19\n\x11widget_wrapper_id\x18\x01 \x01(\t\x12\x12\n\nwidget_url\x18\x03 \x01(\tJ\x04\x08\x02\x10\x03J\x04\x08\x04\x10\x0b\x42@\n\x16\x63om.hotstar.bff.api.v2P\x01Z$github.com/hotstar/hs-core-api-go/v2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v2.refresh_widget_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.hotstar.bff.api.v2P\001Z$github.com/hotstar/hs-core-api-go/v2'
  _globals['_REFRESHWIDGETREQUEST'].fields_by_name['widget_wrapper_id']._loaded_options = None
  _globals['_REFRESHWIDGETREQUEST'].fields_by_name['widget_wrapper_id']._serialized_options = b'\030\001'
  _globals['_REFRESHWIDGETREQUEST']._loaded_options = None
  _globals['_REFRESHWIDGETREQUEST']._serialized_options = b'\030\001'
  _globals['_REFRESHWIDGETREQUEST']._serialized_start=31
  _globals['_REFRESHWIDGETREQUEST']._serialized_end=120
  _globals['_DEFERREDWIDGETREQUEST']._serialized_start=122
  _globals['_DEFERREDWIDGETREQUEST']._serialized_end=204
# @@protoc_insertion_point(module_scope)
