# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/context/widget/client_widget.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/context/widget/client_widget.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from options import opts_pb2 as options_dot_opts__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)client/context/widget/client_widget.proto\x12\x15\x63lient.context.widget\x1a\x12options/opts.proto\"\x8b\x01\n\x0c\x43lientWidget\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\r\n\x05logic\x18\x05 \x01(\t\x12\x18\n\x10\x64isplay_language\x18\x06 \x01(\t\x12\x10\n\x08position\x18\x07 \x01(\x03\x12\x14\n\x0c\x64iscovery_id\x18\x08 \x01(\tB}\n-com.hotstar.event.model.client.context.widgetP\x01ZJgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/context/widgetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.context.widget.client_widget_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n-com.hotstar.event.model.client.context.widgetP\001ZJgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/context/widget'
  _globals['_CLIENTWIDGET']._serialized_start=89
  _globals['_CLIENTWIDGET']._serialized_end=228
# @@protoc_insertion_point(module_scope)
