# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/heartbeat/model/viewport.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/heartbeat/model/viewport.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%client/heartbeat/model/viewport.proto\x12\x16\x63lient.heartbeat.model*e\n\x08Viewport\x12\x18\n\x14VIEWPORT_UNSPECIFIED\x10\x00\x12\x15\n\x11VIEWPORT_PORTRAIT\x10\x01\x12\x16\n\x12VIEWPORT_LANDSCAPE\x10\x02\x12\x10\n\x0cVIEWPORT_PIP\x10\x03\x42\x7f\n.com.hotstar.event.model.client.heartbeat.modelP\x01ZKgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/heartbeat/modelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.heartbeat.model.viewport_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n.com.hotstar.event.model.client.heartbeat.modelP\001ZKgithub.com/hotstar/data-event-schemas-go/hsanalytics/client/heartbeat/model'
  _globals['_VIEWPORT']._serialized_start=65
  _globals['_VIEWPORT']._serialized_end=166
# @@protoc_insertion_point(module_scope)
