# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feature/model/app_permission.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'feature/model/app_permission.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"feature/model/app_permission.proto\x12\rfeature.model*0\n\rAppPermission\x12\x08\n\x04NONE\x10\x00\x12\x15\n\x11PUSH_NOTIFICATION\x10\x01\x42]\n\"com.hotstar.ui.model.feature.modelP\x01Z5github.com/hotstar/hs-core-ui-models-go/feature/modelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feature.model.app_permission_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"com.hotstar.ui.model.feature.modelP\001Z5github.com/hotstar/hs-core-ui-models-go/feature/model'
  _globals['_APPPERMISSION']._serialized_start=53
  _globals['_APPPERMISSION']._serialized_end=101
# @@protoc_insertion_point(module_scope)
