# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client/ads/error.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'client/ads/error.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from client.ads import info_pb2 as client_dot_ads_dot_info__pb2
from options import opts_pb2 as options_dot_opts__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63lient/ads/error.proto\x12\nclient.ads\x1a\x15\x63lient/ads/info.proto\x1a\x12options/opts.proto\"\xcc\x01\n\x05\x45rror\x12\x12\n\nerror_type\x18\x01 \x01(\t\x12\x16\n\nerror_code\x18\x02 \x01(\tB\x02\x18\x01\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x17\n\x0b\x63\x61mpaign_id\x18\x04 \x01(\tB\x02\x18\x01\x12\x13\n\x07id_list\x18\x05 \x01(\tB\x02\x18\x01\x12\x13\n\x07goal_id\x18\x06 \x01(\tB\x02\x18\x01\x12\x1e\n\x04info\x18\x07 \x01(\x0b\x32\x10.client.ads.Info\x12\x0b\n\x03url\x18\x08 \x01(\t\x12\x10\n\x08\x65rr_code\x18\t \x01(\rBg\n\"com.hotstar.event.model.client.adsP\x01Z?github.com/hotstar/data-event-schemas-go/hsanalytics/client/adsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.ads.error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"com.hotstar.event.model.client.adsP\001Z?github.com/hotstar/data-event-schemas-go/hsanalytics/client/ads'
  _globals['_ERROR'].fields_by_name['error_code']._loaded_options = None
  _globals['_ERROR'].fields_by_name['error_code']._serialized_options = b'\030\001'
  _globals['_ERROR'].fields_by_name['campaign_id']._loaded_options = None
  _globals['_ERROR'].fields_by_name['campaign_id']._serialized_options = b'\030\001'
  _globals['_ERROR'].fields_by_name['id_list']._loaded_options = None
  _globals['_ERROR'].fields_by_name['id_list']._serialized_options = b'\030\001'
  _globals['_ERROR'].fields_by_name['goal_id']._loaded_options = None
  _globals['_ERROR'].fields_by_name['goal_id']._serialized_options = b'\030\001'
  _globals['_ERROR']._serialized_start=82
  _globals['_ERROR']._serialized_end=286
# @@protoc_insertion_point(module_scope)
