# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/feature/identity/account.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'api/feature/identity/account.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from options import opts_pb2 as options_dot_opts__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"api/feature/identity/account.proto\x12\x14\x61pi.feature.identity\x1a\x12options/opts.proto\"\xc6\x02\n\x07\x41\x63\x63ount\x12\x43\n\naccount_id\x18\x02 \x01(\x0b\x32/.api.feature.identity.Account.AccountIdentifier\x12\x37\n\x04type\x18\x03 \x01(\x0e\x32).api.feature.identity.Account.AccountType\x1a.\n\x11\x41\x63\x63ountIdentifier\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x64w_id\x18\x02 \x01(\t\"\x8c\x01\n\x0b\x41\x63\x63ountType\x12\x1c\n\x18\x41\x43\x43OUNT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n\x12\x41\x43\x43OUNT_TYPE_GUEST\x10\x01\x12\x16\n\x12\x41\x43\x43OUNT_TYPE_PHONE\x10\x02\x12\x16\n\x12\x41\x43\x43OUNT_TYPE_EMAIL\x10\x03\x12\x17\n\x13\x41\x43\x43OUNT_TYPE_DEVICE\x10\x04\x42{\n,com.hotstar.event.model.api.feature.identityP\x01ZIgithub.com/hotstar/data-event-schemas-go/hsanalytics/api/feature/identityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.feature.identity.account_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n,com.hotstar.event.model.api.feature.identityP\001ZIgithub.com/hotstar/data-event-schemas-go/hsanalytics/api/feature/identity'
  _globals['_ACCOUNT']._serialized_start=81
  _globals['_ACCOUNT']._serialized_end=407
  _globals['_ACCOUNT_ACCOUNTIDENTIFIER']._serialized_start=218
  _globals['_ACCOUNT_ACCOUNTIDENTIFIER']._serialized_end=264
  _globals['_ACCOUNT_ACCOUNTTYPE']._serialized_start=267
  _globals['_ACCOUNT_ACCOUNTTYPE']._serialized_end=407
# @@protoc_insertion_point(module_scope)
