# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v2/response/space_response.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'v2/response/space_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v2 import space_pb2 as v2_dot_space__pb2
from v2 import error_pb2 as v2_dot_error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n v2/response/space_response.proto\x12\x0bv2.response\x1a\x0ev2/space.proto\x1a\x0ev2/error.proto\"\x83\x01\n\rSpaceResponse\x12\x33\n\x07success\x18\x01 \x01(\x0b\x32\".v2.response.SpaceResponse.Success\x12\x18\n\x05\x65rror\x18\x02 \x01(\x0b\x32\t.v2.Error\x1a#\n\x07Success\x12\x18\n\x05space\x18\x01 \x01(\x0b\x32\t.v2.SpaceBR\n\x1f\x63om.hotstar.bff.api.v2.responseP\x01Z-github.com/hotstar/hs-core-api-go/v2/responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v2.response.space_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037com.hotstar.bff.api.v2.responseP\001Z-github.com/hotstar/hs-core-api-go/v2/response'
  _globals['_SPACERESPONSE']._serialized_start=82
  _globals['_SPACERESPONSE']._serialized_end=213
  _globals['_SPACERESPONSE_SUCCESS']._serialized_start=178
  _globals['_SPACERESPONSE_SUCCESS']._serialized_end=213
# @@protoc_insertion_point(module_scope)
